/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_BPT_UBA_PROTO_BPT_PB_H_INCLUDED
#define PB_UBA_PROTO_BPT_UBA_PROTO_BPT_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_UBA6.pb.h"
#include "UBA_PROTO_CHANNEL.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_BPT_STEP_TYPE {
    UBA_PROTO_BPT_STEP_TYPE_CHARGE = 0,
    UBA_PROTO_BPT_STEP_TYPE_DISCHARGE = 1,
    UBA_PROTO_BPT_STEP_TYPE_DELAY = 2,
    UBA_PROTO_BPT_STEP_TYPE_MAX = 3,
    UBA_PROTO_BPT_STEP_TYPE_INVALID = 4
} UBA_PROTO_BPT_STEP_TYPE;

typedef enum _UBA_PROTO_BPT_MODE {
    UBA_PROTO_BPT_MODE_SINGLE_CHANNEL = 0,
    UBA_PROTO_BPT_MODE_DUAL_CHANNEL = 1,
    UBA_PROTO_BPT_MODE_MODE_MAX = 2,
    UBA_PROTO_BPT_MODE_MODE_INVALED = 3
} UBA_PROTO_BPT_MODE;

typedef enum _UBA_PROTO_BPT_SOURCE {
    UBA_PROTO_BPT_SOURCE_INTERNAL = 0,
    UBA_PROTO_BPT_SOURCE_EXTERNAL = 1,
    UBA_PROTO_BPT_SOURCE_SOURCE_MAX = 2
} UBA_PROTO_BPT_SOURCE;

typedef enum _UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE {
    UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_ABSOLUTE = 0,
    UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_POWER = 1,
    UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_RESISTANCE = 2,
    UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_TYPE_MAX = 3
} UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE;

typedef enum _UBA_PROTO_BPT_STATE {
    UBA_PROTO_BPT_STATE_INIT = 0,
    UBA_PROTO_BPT_STATE_STANDBY = 1,
    UBA_PROTO_BPT_STATE_PAUSE = 2,
    UBA_PROTO_BPT_STATE_RUN_STEP = 3,
    UBA_PROTO_BPT_STATE_STEP_COMPLEATE = 4,
    UBA_PROTO_BPT_STATE_TEST_FAILED = 5,
    UBA_PROTO_BPT_STATE_TEST_COMPLEATE = 6,
    UBA_PROTO_BPT_STATE_STATE_MAX = 7,
    UBA_PROTO_BPT_STATE_STATE_INVALID = 8
} UBA_PROTO_BPT_STATE;

typedef enum _UBA_PROTO_BPT_CMD_ID {
    UBA_PROTO_BPT_CMD_ID_TEST = 0,
    UBA_PROTO_BPT_CMD_ID_SELECT = 1, /* start BPT */
    UBA_PROTO_BPT_CMD_ID_STOP = 2, /* stop bpt */
    UBA_PROTO_BPT_CMD_ID_PAUSED = 3, /* stop bpt */
    UBA_PROTO_BPT_CMD_ID_CLEAR = 4 /* Clear the BPT reset errro and set to STANDBY */
} UBA_PROTO_BPT_CMD_ID;

/* Struct definitions */
typedef struct _UBA_PROTO_BPT_discharge_current {
    UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE type;
    int32_t value;
} UBA_PROTO_BPT_discharge_current;

typedef struct _UBA_PROTO_BPT_charge_stop_condition {
    float max_temperature; /* the max temp in c */
    uint32_t max_time; /* the max time in ms */
    int32_t cut_off_current; /* the current of charge that below it the step will end */
    int32_t limit_capacity; /* the capacity in mAh that above it the step will end */
} UBA_PROTO_BPT_charge_stop_condition;

typedef struct _UBA_PROTO_BPT_charge {
    UBA_PROTO_BPT_SOURCE source; /* select the source that the charge will occur */
    int32_t current; /* the charge current in mA the device must keep this current whill charging */
    /* TODO: Cehck if current can be negtive and if max current can be  2^31 */
    int32_t voltage; /* the end voltage that the deivce need to charge the battery */
    float min_temperature; /* below this temp the device will not charge */
    UBA_PROTO_BPT_charge_stop_condition sc;
} UBA_PROTO_BPT_charge;

typedef struct _UBA_PROTO_BPT_discharge_stop_condition {
    float max_temperature; /* the max temp in c */
    uint32_t max_time; /* the max time in ms */
    int32_t cut_off_voltag; /* the voltage that the battery will reatch that stop the step */
    int32_t limit_capacity; /* the capacity in mAh that above it the step will end */
} UBA_PROTO_BPT_discharge_stop_condition;

typedef struct _UBA_PROTO_BPT_discharge {
    UBA_PROTO_BPT_SOURCE source; /* select the source that the charge will occur */
    UBA_PROTO_BPT_discharge_current current; /* the dischrage value */
    float min_temperature;
    UBA_PROTO_BPT_discharge_stop_condition sc;
} UBA_PROTO_BPT_discharge;

typedef struct _UBA_PROTO_BPT_delay {
    uint32_t delay_time;
    float cool_down_temperature;
} UBA_PROTO_BPT_delay;

typedef struct _UBA_PROTO_BPT_BPT {
    UBA_PROTO_BPT_STATE state;
} UBA_PROTO_BPT_BPT;

typedef struct _UBA_PROTO_BPT_data_log_message {
    UBA_PROTO_CHANNEL_ID channelID;
    uint32_t timestamp;
    uint32_t current_step;
} UBA_PROTO_BPT_data_log_message;

typedef struct _UBA_PROTO_BPT_command {
    UBA_PROTO_BPT_CMD_ID id;
    UBA_PROTO_CHANNEL_ID channel;
    uint8_t BPT_list_entery;
} UBA_PROTO_BPT_command;

typedef struct _UBA_PROTO_BPT_status_message {
    UBA_PROTO_UBA6_ERROR error;
    UBA_PROTO_BPT_STATE state;
    uint32_t start_time;
    uint8_t current_step;
    UBA_PROTO_BPT_STEP_TYPE step_type;
    uint8_t total_steps;
    UBA_PROTO_CHANNEL_status channel_status;
} UBA_PROTO_BPT_status_message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_BPT_STEP_TYPE_MIN UBA_PROTO_BPT_STEP_TYPE_CHARGE
#define _UBA_PROTO_BPT_STEP_TYPE_MAX UBA_PROTO_BPT_STEP_TYPE_INVALID
#define _UBA_PROTO_BPT_STEP_TYPE_ARRAYSIZE ((UBA_PROTO_BPT_STEP_TYPE)(UBA_PROTO_BPT_STEP_TYPE_INVALID+1))

#define _UBA_PROTO_BPT_MODE_MIN UBA_PROTO_BPT_MODE_SINGLE_CHANNEL
#define _UBA_PROTO_BPT_MODE_MAX UBA_PROTO_BPT_MODE_MODE_INVALED
#define _UBA_PROTO_BPT_MODE_ARRAYSIZE ((UBA_PROTO_BPT_MODE)(UBA_PROTO_BPT_MODE_MODE_INVALED+1))

#define _UBA_PROTO_BPT_SOURCE_MIN UBA_PROTO_BPT_SOURCE_INTERNAL
#define _UBA_PROTO_BPT_SOURCE_MAX UBA_PROTO_BPT_SOURCE_SOURCE_MAX
#define _UBA_PROTO_BPT_SOURCE_ARRAYSIZE ((UBA_PROTO_BPT_SOURCE)(UBA_PROTO_BPT_SOURCE_SOURCE_MAX+1))

#define _UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_MIN UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_ABSOLUTE
#define _UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_MAX UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_TYPE_MAX
#define _UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_ARRAYSIZE ((UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE)(UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_TYPE_MAX+1))

#define _UBA_PROTO_BPT_STATE_MIN UBA_PROTO_BPT_STATE_INIT
#define _UBA_PROTO_BPT_STATE_MAX UBA_PROTO_BPT_STATE_STATE_INVALID
#define _UBA_PROTO_BPT_STATE_ARRAYSIZE ((UBA_PROTO_BPT_STATE)(UBA_PROTO_BPT_STATE_STATE_INVALID+1))

#define _UBA_PROTO_BPT_CMD_ID_MIN UBA_PROTO_BPT_CMD_ID_TEST
#define _UBA_PROTO_BPT_CMD_ID_MAX UBA_PROTO_BPT_CMD_ID_CLEAR
#define _UBA_PROTO_BPT_CMD_ID_ARRAYSIZE ((UBA_PROTO_BPT_CMD_ID)(UBA_PROTO_BPT_CMD_ID_CLEAR+1))

#define UBA_PROTO_BPT_discharge_current_type_ENUMTYPE UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE


#define UBA_PROTO_BPT_charge_source_ENUMTYPE UBA_PROTO_BPT_SOURCE


#define UBA_PROTO_BPT_discharge_source_ENUMTYPE UBA_PROTO_BPT_SOURCE


#define UBA_PROTO_BPT_BPT_state_ENUMTYPE UBA_PROTO_BPT_STATE

#define UBA_PROTO_BPT_data_log_message_channelID_ENUMTYPE UBA_PROTO_CHANNEL_ID

#define UBA_PROTO_BPT_command_id_ENUMTYPE UBA_PROTO_BPT_CMD_ID
#define UBA_PROTO_BPT_command_channel_ENUMTYPE UBA_PROTO_CHANNEL_ID

#define UBA_PROTO_BPT_status_message_error_ENUMTYPE UBA_PROTO_UBA6_ERROR
#define UBA_PROTO_BPT_status_message_state_ENUMTYPE UBA_PROTO_BPT_STATE
#define UBA_PROTO_BPT_status_message_step_type_ENUMTYPE UBA_PROTO_BPT_STEP_TYPE


/* Initializer values for message structs */
#define UBA_PROTO_BPT_discharge_current_init_default {_UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_MIN, 0}
#define UBA_PROTO_BPT_charge_stop_condition_init_default {0, 0, 0, 0}
#define UBA_PROTO_BPT_charge_init_default        {_UBA_PROTO_BPT_SOURCE_MIN, 0, 0, 0, UBA_PROTO_BPT_charge_stop_condition_init_default}
#define UBA_PROTO_BPT_discharge_stop_condition_init_default {0, 0, 0, 0}
#define UBA_PROTO_BPT_discharge_init_default     {_UBA_PROTO_BPT_SOURCE_MIN, UBA_PROTO_BPT_discharge_current_init_default, 0, UBA_PROTO_BPT_discharge_stop_condition_init_default}
#define UBA_PROTO_BPT_delay_init_default         {0, 0}
#define UBA_PROTO_BPT_BPT_init_default           {_UBA_PROTO_BPT_STATE_MIN}
#define UBA_PROTO_BPT_data_log_message_init_default {_UBA_PROTO_CHANNEL_ID_MIN, 0, 0}
#define UBA_PROTO_BPT_command_init_default       {_UBA_PROTO_BPT_CMD_ID_MIN, _UBA_PROTO_CHANNEL_ID_MIN, 0}
#define UBA_PROTO_BPT_status_message_init_default {_UBA_PROTO_UBA6_ERROR_MIN, _UBA_PROTO_BPT_STATE_MIN, 0, 0, _UBA_PROTO_BPT_STEP_TYPE_MIN, 0, UBA_PROTO_CHANNEL_status_init_default}
#define UBA_PROTO_BPT_discharge_current_init_zero {_UBA_PROTO_BPT_DISCHARGE_CURRENT_TYPE_MIN, 0}
#define UBA_PROTO_BPT_charge_stop_condition_init_zero {0, 0, 0, 0}
#define UBA_PROTO_BPT_charge_init_zero           {_UBA_PROTO_BPT_SOURCE_MIN, 0, 0, 0, UBA_PROTO_BPT_charge_stop_condition_init_zero}
#define UBA_PROTO_BPT_discharge_stop_condition_init_zero {0, 0, 0, 0}
#define UBA_PROTO_BPT_discharge_init_zero        {_UBA_PROTO_BPT_SOURCE_MIN, UBA_PROTO_BPT_discharge_current_init_zero, 0, UBA_PROTO_BPT_discharge_stop_condition_init_zero}
#define UBA_PROTO_BPT_delay_init_zero            {0, 0}
#define UBA_PROTO_BPT_BPT_init_zero              {_UBA_PROTO_BPT_STATE_MIN}
#define UBA_PROTO_BPT_data_log_message_init_zero {_UBA_PROTO_CHANNEL_ID_MIN, 0, 0}
#define UBA_PROTO_BPT_command_init_zero          {_UBA_PROTO_BPT_CMD_ID_MIN, _UBA_PROTO_CHANNEL_ID_MIN, 0}
#define UBA_PROTO_BPT_status_message_init_zero   {_UBA_PROTO_UBA6_ERROR_MIN, _UBA_PROTO_BPT_STATE_MIN, 0, 0, _UBA_PROTO_BPT_STEP_TYPE_MIN, 0, UBA_PROTO_CHANNEL_status_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_BPT_discharge_current_type_tag 1
#define UBA_PROTO_BPT_discharge_current_value_tag 2
#define UBA_PROTO_BPT_charge_stop_condition_max_temperature_tag 1
#define UBA_PROTO_BPT_charge_stop_condition_max_time_tag 2
#define UBA_PROTO_BPT_charge_stop_condition_cut_off_current_tag 3
#define UBA_PROTO_BPT_charge_stop_condition_limit_capacity_tag 4
#define UBA_PROTO_BPT_charge_source_tag          1
#define UBA_PROTO_BPT_charge_current_tag         2
#define UBA_PROTO_BPT_charge_voltage_tag         3
#define UBA_PROTO_BPT_charge_min_temperature_tag 4
#define UBA_PROTO_BPT_charge_sc_tag              5
#define UBA_PROTO_BPT_discharge_stop_condition_max_temperature_tag 1
#define UBA_PROTO_BPT_discharge_stop_condition_max_time_tag 2
#define UBA_PROTO_BPT_discharge_stop_condition_cut_off_voltag_tag 3
#define UBA_PROTO_BPT_discharge_stop_condition_limit_capacity_tag 4
#define UBA_PROTO_BPT_discharge_source_tag       1
#define UBA_PROTO_BPT_discharge_current_tag      2
#define UBA_PROTO_BPT_discharge_min_temperature_tag 3
#define UBA_PROTO_BPT_discharge_sc_tag           4
#define UBA_PROTO_BPT_delay_delay_time_tag       1
#define UBA_PROTO_BPT_delay_cool_down_temperature_tag 2
#define UBA_PROTO_BPT_BPT_state_tag              1
#define UBA_PROTO_BPT_data_log_message_channelID_tag 1
#define UBA_PROTO_BPT_data_log_message_timestamp_tag 2
#define UBA_PROTO_BPT_data_log_message_current_step_tag 3
#define UBA_PROTO_BPT_command_id_tag             1
#define UBA_PROTO_BPT_command_channel_tag        2
#define UBA_PROTO_BPT_command_BPT_list_entery_tag 3
#define UBA_PROTO_BPT_status_message_error_tag   1
#define UBA_PROTO_BPT_status_message_state_tag   2
#define UBA_PROTO_BPT_status_message_start_time_tag 3
#define UBA_PROTO_BPT_status_message_current_step_tag 4
#define UBA_PROTO_BPT_status_message_step_type_tag 5
#define UBA_PROTO_BPT_status_message_total_steps_tag 6
#define UBA_PROTO_BPT_status_message_channel_status_tag 7

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_BPT_discharge_current_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    value,             2)
#define UBA_PROTO_BPT_discharge_current_CALLBACK NULL
#define UBA_PROTO_BPT_discharge_current_DEFAULT NULL

#define UBA_PROTO_BPT_charge_stop_condition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    max_temperature,   1) \
X(a, STATIC,   SINGULAR, UINT32,   max_time,          2) \
X(a, STATIC,   SINGULAR, INT32,    cut_off_current,   3) \
X(a, STATIC,   SINGULAR, INT32,    limit_capacity,    4)
#define UBA_PROTO_BPT_charge_stop_condition_CALLBACK NULL
#define UBA_PROTO_BPT_charge_stop_condition_DEFAULT NULL

#define UBA_PROTO_BPT_charge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    source,            1) \
X(a, STATIC,   SINGULAR, INT32,    current,           2) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    min_temperature,   4) \
X(a, STATIC,   SINGULAR, MESSAGE,  sc,                5)
#define UBA_PROTO_BPT_charge_CALLBACK NULL
#define UBA_PROTO_BPT_charge_DEFAULT NULL
#define UBA_PROTO_BPT_charge_sc_MSGTYPE UBA_PROTO_BPT_charge_stop_condition

#define UBA_PROTO_BPT_discharge_stop_condition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    max_temperature,   1) \
X(a, STATIC,   SINGULAR, UINT32,   max_time,          2) \
X(a, STATIC,   SINGULAR, INT32,    cut_off_voltag,    3) \
X(a, STATIC,   SINGULAR, INT32,    limit_capacity,    4)
#define UBA_PROTO_BPT_discharge_stop_condition_CALLBACK NULL
#define UBA_PROTO_BPT_discharge_stop_condition_DEFAULT NULL

#define UBA_PROTO_BPT_discharge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    source,            1) \
X(a, STATIC,   SINGULAR, MESSAGE,  current,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    min_temperature,   3) \
X(a, STATIC,   SINGULAR, MESSAGE,  sc,                4)
#define UBA_PROTO_BPT_discharge_CALLBACK NULL
#define UBA_PROTO_BPT_discharge_DEFAULT NULL
#define UBA_PROTO_BPT_discharge_current_MSGTYPE UBA_PROTO_BPT_discharge_current
#define UBA_PROTO_BPT_discharge_sc_MSGTYPE UBA_PROTO_BPT_discharge_stop_condition

#define UBA_PROTO_BPT_delay_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   delay_time,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    cool_down_temperature,   2)
#define UBA_PROTO_BPT_delay_CALLBACK NULL
#define UBA_PROTO_BPT_delay_DEFAULT NULL

#define UBA_PROTO_BPT_BPT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define UBA_PROTO_BPT_BPT_CALLBACK NULL
#define UBA_PROTO_BPT_BPT_DEFAULT NULL

#define UBA_PROTO_BPT_data_log_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    channelID,         1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         2) \
X(a, STATIC,   SINGULAR, UINT32,   current_step,      3)
#define UBA_PROTO_BPT_data_log_message_CALLBACK NULL
#define UBA_PROTO_BPT_data_log_message_DEFAULT NULL

#define UBA_PROTO_BPT_command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    channel,           2) \
X(a, STATIC,   SINGULAR, UINT32,   BPT_list_entery,   3)
#define UBA_PROTO_BPT_command_CALLBACK NULL
#define UBA_PROTO_BPT_command_DEFAULT NULL

#define UBA_PROTO_BPT_status_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   start_time,        3) \
X(a, STATIC,   SINGULAR, UINT32,   current_step,      4) \
X(a, STATIC,   SINGULAR, UENUM,    step_type,         5) \
X(a, STATIC,   SINGULAR, UINT32,   total_steps,       6) \
X(a, STATIC,   SINGULAR, MESSAGE,  channel_status,    7)
#define UBA_PROTO_BPT_status_message_CALLBACK NULL
#define UBA_PROTO_BPT_status_message_DEFAULT NULL
#define UBA_PROTO_BPT_status_message_channel_status_MSGTYPE UBA_PROTO_CHANNEL_status

extern const pb_msgdesc_t UBA_PROTO_BPT_discharge_current_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_charge_stop_condition_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_charge_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_discharge_stop_condition_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_discharge_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_delay_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_BPT_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_data_log_message_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_command_msg;
extern const pb_msgdesc_t UBA_PROTO_BPT_status_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_BPT_discharge_current_fields &UBA_PROTO_BPT_discharge_current_msg
#define UBA_PROTO_BPT_charge_stop_condition_fields &UBA_PROTO_BPT_charge_stop_condition_msg
#define UBA_PROTO_BPT_charge_fields &UBA_PROTO_BPT_charge_msg
#define UBA_PROTO_BPT_discharge_stop_condition_fields &UBA_PROTO_BPT_discharge_stop_condition_msg
#define UBA_PROTO_BPT_discharge_fields &UBA_PROTO_BPT_discharge_msg
#define UBA_PROTO_BPT_delay_fields &UBA_PROTO_BPT_delay_msg
#define UBA_PROTO_BPT_BPT_fields &UBA_PROTO_BPT_BPT_msg
#define UBA_PROTO_BPT_data_log_message_fields &UBA_PROTO_BPT_data_log_message_msg
#define UBA_PROTO_BPT_command_fields &UBA_PROTO_BPT_command_msg
#define UBA_PROTO_BPT_status_message_fields &UBA_PROTO_BPT_status_message_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_BPT_BPT_size                   2
#define UBA_PROTO_BPT_UBA_PROTO_BPT_PB_H_MAX_SIZE UBA_PROTO_BPT_status_message_size
#define UBA_PROTO_BPT_charge_size                64
#define UBA_PROTO_BPT_charge_stop_condition_size 33
#define UBA_PROTO_BPT_command_size               7
#define UBA_PROTO_BPT_data_log_message_size      14
#define UBA_PROTO_BPT_delay_size                 11
#define UBA_PROTO_BPT_discharge_current_size     13
#define UBA_PROTO_BPT_discharge_size             57
#define UBA_PROTO_BPT_discharge_stop_condition_size 33
#define UBA_PROTO_BPT_status_message_size        308

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
