/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_UBA6_UBA_PROTO_UBA6_PB_H_INCLUDED
#define PB_UBA_PROTO_UBA6_UBA_PROTO_UBA6_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_UBA6_STATE {
    UBA_PROTO_UBA6_STATE_INIT = 0,
    UBA_PROTO_UBA6_STATE_SINGLE_CHANNELS = 1,
    UBA_PROTO_UBA6_STATE_DUAL_CHANNEL = 2
} UBA_PROTO_UBA6_STATE;

typedef enum _UBA_PROTO_UBA6_ERROR {
    UBA_PROTO_UBA6_ERROR_NO_ERROR = 0,
    UBA_PROTO_UBA6_ERROR_LINE_NOT_AVAILABLE = 1,
    UBA_PROTO_UBA6_ERROR_LINE_I2C_PERIPHERAL = 2,
    UBA_PROTO_UBA6_ERROR_LINE_BAT_HIGH_VOLTAGE = 4,
    UBA_PROTO_UBA6_ERROR_LINE_BAT_HIGH_CURRENT = 8,
    UBA_PROTO_UBA6_ERROR_LINE_BAT_HIGH_TEMP = 16,
    UBA_PROTO_UBA6_ERROR_LINE_AMB_HIGH_TEMP = 32,
    UBA_PROTO_UBA6_ERROR_LINE_GEN_HIGH_VOLTAGE = 64,
    UBA_PROTO_UBA6_ERROR_LINE_BIST_FALIED = 128,
    UBA_PROTO_UBA6_ERROR_LINE_BUSY = 256,
    UBA_PROTO_UBA6_ERROR_LINE_REVERSE_POLARITY = 512,
    UBA_PROTO_UBA6_ERROR_LINE_OVER_VOLTAGE = 1024,
    UBA_PROTO_UBA6_ERROR_LINE_DISCHARGE_MOSFET_SHORT = 2048,
    UBA_PROTO_UBA6_ERROR_LINE_CHARGE_MOSFET_SHORT = 4096,
    UBA_PROTO_UBA6_ERROR_LINE_LOW_INPUT_VOLTAGE = 8192,
    UBA_PROTO_UBA6_ERROR_LINE_HIGH_INPUT_VOLTAGE = 16384,
    UBA_PROTO_UBA6_ERROR_LINE_VGEN_EXPECTED_MAX_VOLTAGE = 32768,
    UBA_PROTO_UBA6_ERROR_LINE_VGEN_FAILED = 65536, /* VGEN has failed to start */
    UBA_PROTO_UBA6_ERROR_LINE_VGEN_LIMITES = 131072, /* VGEN is reatch the limit */
    UBA_PROTO_UBA6_ERROR_LINE_OVERCURRENT = 262144, /* overcurrent condition detected */
    UBA_PROTO_UBA6_ERROR_LINE_NO_CALIBRATION = 524288, /* calibration file is missing or filed to load */
    UBA_PROTO_UBA6_ERROR_LINE_NOT_CONNECTED = 1048576, /* the battery is not connected */
    UBA_PROTO_UBA6_ERROR_LINE_BAT_TEMP_SENSOR_NC = 2097152, /* the battery temp sensor is not connected */
    UBA_PROTO_UBA6_ERROR_LINE_INTRENAL_TEMP_SENSOR_NC = 4194304, /* the battery temp sensor is not connected */
    UBA_PROTO_UBA6_ERROR_EXTERNAL_LINE_ERROR = 8388608, /* an external error is detected form external control */
    UBA_PROTO_UBA6_ERROR_INTRENAL_LINE_ERROR = 16777216, /* an internal error is detected */
    UBA_PROTO_UBA6_ERROR_CHANNEL_EMPTY = 33554432, /* the channel has no lines connected */
    UBA_PROTO_UBA6_ERROR_CHANNEL_MULTI_LINE_VOLTAGE_MISMATCH = 67108864, /* the lines in the channel have different voltages */
    UBA_PROTO_UBA6_ERROR_CHANNEL_MULTI_LINE_CURRENT_MISMATCH = 134217728, /* the lines in the channel have different currents */
    UBA_PROTO_UBA6_ERROR_SD_CARD = 268435456, /* SD card error */
    UBA_PROTO_UBA6_ERROR_USER_ABORT = 536870912, /* the user has aborted the operation */
    UBA_PROTO_UBA6_ERROR_CHANNEL_ERROR = 1073741824 /* generic channel error */
} UBA_PROTO_UBA6_ERROR;

typedef enum _UBA_PROTO_UBA6_CMD_ID {
    UBA_PROTO_UBA6_CMD_ID_TEST = 0,
    UBA_PROTO_UBA6_CMD_ID_ADDRESSS = 1, /* chnage address value 1-32 */
    UBA_PROTO_UBA6_CMD_ID_BUZZER = 2, /* mute/unmute buzzer */
    UBA_PROTO_UBA6_CMD_ID_MODE = 3, /* set mode single chnaggle dual channel */
    UBA_PROTO_UBA6_CMD_ID_NAME = 4, /* rename the device */
    UBA_PROTO_UBA6_CMD_ID_TIME = 5, /* set the time of the device */
    UBA_PROTO_UBA6_CMD_ID_BOOT = 6, /* reboot the device */
    UBA_PROTO_UBA6_CMD_ID_SN = 7 /* set the serial number of the device */
} UBA_PROTO_UBA6_CMD_ID;

/* Struct definitions */
typedef struct _UBA_PROTO_UBA6_firmware_message {
    uint16_t major;
    uint16_t minor;
    uint16_t patch;
    uint16_t build;
} UBA_PROTO_UBA6_firmware_message;

typedef struct _UBA_PROTO_UBA6_hardware_revision_message {
    uint16_t major;
    uint16_t minor;
} UBA_PROTO_UBA6_hardware_revision_message;

typedef struct _UBA_PROTO_UBA6_serial_number {
    uint8_t constant;
    uint8_t year;
    uint8_t week;
    uint16_t number;
} UBA_PROTO_UBA6_serial_number;

typedef struct _UBA_PROTO_UBA6_settings {
    uint32_t SN; /* the serial number of the device */
    uint32_t address; /* the address of the device 1-32 */
    char name[32]; /* the name of the device */
    uint8_t buzzer;
} UBA_PROTO_UBA6_settings;

typedef struct _UBA_PROTO_UBA6_info {
    UBA_PROTO_UBA6_firmware_message firmware;
    UBA_PROTO_UBA6_hardware_revision_message revision;
    uint32_t rtc; /* the time of the device in unix format */
    UBA_PROTO_UBA6_STATE state; /* the current state of the device */
    UBA_PROTO_UBA6_ERROR error; /* the current error of the device */
} UBA_PROTO_UBA6_info;

typedef struct _UBA_PROTO_UBA6_status {
    UBA_PROTO_UBA6_settings settings; /* the setting of the device , retrive form file can be change in factory */
    UBA_PROTO_UBA6_info info; /* the info of the device , the info and status of the device */
} UBA_PROTO_UBA6_status;

typedef struct _UBA_PROTO_UBA6_command {
    UBA_PROTO_UBA6_CMD_ID id;
    uint32_t value; /* the value of the command */
    char name[32]; /* reanme the device */
} UBA_PROTO_UBA6_command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_UBA6_STATE_MIN UBA_PROTO_UBA6_STATE_INIT
#define _UBA_PROTO_UBA6_STATE_MAX UBA_PROTO_UBA6_STATE_DUAL_CHANNEL
#define _UBA_PROTO_UBA6_STATE_ARRAYSIZE ((UBA_PROTO_UBA6_STATE)(UBA_PROTO_UBA6_STATE_DUAL_CHANNEL+1))

#define _UBA_PROTO_UBA6_ERROR_MIN UBA_PROTO_UBA6_ERROR_NO_ERROR
#define _UBA_PROTO_UBA6_ERROR_MAX UBA_PROTO_UBA6_ERROR_CHANNEL_ERROR
#define _UBA_PROTO_UBA6_ERROR_ARRAYSIZE ((UBA_PROTO_UBA6_ERROR)(UBA_PROTO_UBA6_ERROR_CHANNEL_ERROR+1))

#define _UBA_PROTO_UBA6_CMD_ID_MIN UBA_PROTO_UBA6_CMD_ID_TEST
#define _UBA_PROTO_UBA6_CMD_ID_MAX UBA_PROTO_UBA6_CMD_ID_SN
#define _UBA_PROTO_UBA6_CMD_ID_ARRAYSIZE ((UBA_PROTO_UBA6_CMD_ID)(UBA_PROTO_UBA6_CMD_ID_SN+1))





#define UBA_PROTO_UBA6_info_state_ENUMTYPE UBA_PROTO_UBA6_STATE
#define UBA_PROTO_UBA6_info_error_ENUMTYPE UBA_PROTO_UBA6_ERROR


#define UBA_PROTO_UBA6_command_id_ENUMTYPE UBA_PROTO_UBA6_CMD_ID


/* Initializer values for message structs */
#define UBA_PROTO_UBA6_firmware_message_init_default {0, 0, 0, 0}
#define UBA_PROTO_UBA6_hardware_revision_message_init_default {0, 0}
#define UBA_PROTO_UBA6_serial_number_init_default {0, 0, 0, 0}
#define UBA_PROTO_UBA6_settings_init_default     {0, 0, "", 0}
#define UBA_PROTO_UBA6_info_init_default         {UBA_PROTO_UBA6_firmware_message_init_default, UBA_PROTO_UBA6_hardware_revision_message_init_default, 0, _UBA_PROTO_UBA6_STATE_MIN, _UBA_PROTO_UBA6_ERROR_MIN}
#define UBA_PROTO_UBA6_status_init_default       {UBA_PROTO_UBA6_settings_init_default, UBA_PROTO_UBA6_info_init_default}
#define UBA_PROTO_UBA6_command_init_default      {_UBA_PROTO_UBA6_CMD_ID_MIN, 0, ""}
#define UBA_PROTO_UBA6_firmware_message_init_zero {0, 0, 0, 0}
#define UBA_PROTO_UBA6_hardware_revision_message_init_zero {0, 0}
#define UBA_PROTO_UBA6_serial_number_init_zero   {0, 0, 0, 0}
#define UBA_PROTO_UBA6_settings_init_zero        {0, 0, "", 0}
#define UBA_PROTO_UBA6_info_init_zero            {UBA_PROTO_UBA6_firmware_message_init_zero, UBA_PROTO_UBA6_hardware_revision_message_init_zero, 0, _UBA_PROTO_UBA6_STATE_MIN, _UBA_PROTO_UBA6_ERROR_MIN}
#define UBA_PROTO_UBA6_status_init_zero          {UBA_PROTO_UBA6_settings_init_zero, UBA_PROTO_UBA6_info_init_zero}
#define UBA_PROTO_UBA6_command_init_zero         {_UBA_PROTO_UBA6_CMD_ID_MIN, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_UBA6_firmware_message_major_tag 1
#define UBA_PROTO_UBA6_firmware_message_minor_tag 2
#define UBA_PROTO_UBA6_firmware_message_patch_tag 3
#define UBA_PROTO_UBA6_firmware_message_build_tag 4
#define UBA_PROTO_UBA6_hardware_revision_message_major_tag 1
#define UBA_PROTO_UBA6_hardware_revision_message_minor_tag 2
#define UBA_PROTO_UBA6_serial_number_constant_tag 1
#define UBA_PROTO_UBA6_serial_number_year_tag    2
#define UBA_PROTO_UBA6_serial_number_week_tag    3
#define UBA_PROTO_UBA6_serial_number_number_tag  4
#define UBA_PROTO_UBA6_settings_SN_tag           1
#define UBA_PROTO_UBA6_settings_address_tag      2
#define UBA_PROTO_UBA6_settings_name_tag         3
#define UBA_PROTO_UBA6_settings_buzzer_tag       4
#define UBA_PROTO_UBA6_info_firmware_tag         1
#define UBA_PROTO_UBA6_info_revision_tag         2
#define UBA_PROTO_UBA6_info_rtc_tag              3
#define UBA_PROTO_UBA6_info_state_tag            4
#define UBA_PROTO_UBA6_info_error_tag            5
#define UBA_PROTO_UBA6_status_settings_tag       1
#define UBA_PROTO_UBA6_status_info_tag           2
#define UBA_PROTO_UBA6_command_id_tag            1
#define UBA_PROTO_UBA6_command_value_tag         2
#define UBA_PROTO_UBA6_command_name_tag          3

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_UBA6_firmware_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT32,   patch,             3) \
X(a, STATIC,   SINGULAR, UINT32,   build,             4)
#define UBA_PROTO_UBA6_firmware_message_CALLBACK NULL
#define UBA_PROTO_UBA6_firmware_message_DEFAULT NULL

#define UBA_PROTO_UBA6_hardware_revision_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2)
#define UBA_PROTO_UBA6_hardware_revision_message_CALLBACK NULL
#define UBA_PROTO_UBA6_hardware_revision_message_DEFAULT NULL

#define UBA_PROTO_UBA6_serial_number_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   constant,          1) \
X(a, STATIC,   SINGULAR, UINT32,   year,              2) \
X(a, STATIC,   SINGULAR, UINT32,   week,              3) \
X(a, STATIC,   SINGULAR, UINT32,   number,            4)
#define UBA_PROTO_UBA6_serial_number_CALLBACK NULL
#define UBA_PROTO_UBA6_serial_number_DEFAULT NULL

#define UBA_PROTO_UBA6_settings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   SN,                1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, UINT32,   buzzer,            4)
#define UBA_PROTO_UBA6_settings_CALLBACK NULL
#define UBA_PROTO_UBA6_settings_DEFAULT NULL

#define UBA_PROTO_UBA6_info_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  firmware,          1) \
X(a, STATIC,   SINGULAR, MESSAGE,  revision,          2) \
X(a, STATIC,   SINGULAR, UINT32,   rtc,               3) \
X(a, STATIC,   SINGULAR, UENUM,    state,             4) \
X(a, STATIC,   SINGULAR, UENUM,    error,             5)
#define UBA_PROTO_UBA6_info_CALLBACK NULL
#define UBA_PROTO_UBA6_info_DEFAULT NULL
#define UBA_PROTO_UBA6_info_firmware_MSGTYPE UBA_PROTO_UBA6_firmware_message
#define UBA_PROTO_UBA6_info_revision_MSGTYPE UBA_PROTO_UBA6_hardware_revision_message

#define UBA_PROTO_UBA6_status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  settings,          1) \
X(a, STATIC,   SINGULAR, MESSAGE,  info,              2)
#define UBA_PROTO_UBA6_status_CALLBACK NULL
#define UBA_PROTO_UBA6_status_DEFAULT NULL
#define UBA_PROTO_UBA6_status_settings_MSGTYPE UBA_PROTO_UBA6_settings
#define UBA_PROTO_UBA6_status_info_MSGTYPE UBA_PROTO_UBA6_info

#define UBA_PROTO_UBA6_command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3)
#define UBA_PROTO_UBA6_command_CALLBACK NULL
#define UBA_PROTO_UBA6_command_DEFAULT NULL

extern const pb_msgdesc_t UBA_PROTO_UBA6_firmware_message_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_hardware_revision_message_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_serial_number_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_settings_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_info_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_status_msg;
extern const pb_msgdesc_t UBA_PROTO_UBA6_command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_UBA6_firmware_message_fields &UBA_PROTO_UBA6_firmware_message_msg
#define UBA_PROTO_UBA6_hardware_revision_message_fields &UBA_PROTO_UBA6_hardware_revision_message_msg
#define UBA_PROTO_UBA6_serial_number_fields &UBA_PROTO_UBA6_serial_number_msg
#define UBA_PROTO_UBA6_settings_fields &UBA_PROTO_UBA6_settings_msg
#define UBA_PROTO_UBA6_info_fields &UBA_PROTO_UBA6_info_msg
#define UBA_PROTO_UBA6_status_fields &UBA_PROTO_UBA6_status_msg
#define UBA_PROTO_UBA6_command_fields &UBA_PROTO_UBA6_command_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_UBA6_UBA_PROTO_UBA6_PB_H_MAX_SIZE UBA_PROTO_UBA6_status_size
#define UBA_PROTO_UBA6_command_size              41
#define UBA_PROTO_UBA6_firmware_message_size     16
#define UBA_PROTO_UBA6_hardware_revision_message_size 8
#define UBA_PROTO_UBA6_info_size                 42
#define UBA_PROTO_UBA6_serial_number_size        13
#define UBA_PROTO_UBA6_settings_size             48
#define UBA_PROTO_UBA6_status_size               94

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
