/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_UBA6.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UBA_PROTO_UBA6_firmware_message, UBA_PROTO_UBA6_firmware_message, AUTO)


PB_BIND(UBA_PROTO_UBA6_hardware_revision_message, UBA_PROTO_UBA6_hardware_revision_message, AUTO)


PB_BIND(UBA_PROTO_UBA6_serial_number, UBA_PROTO_UBA6_serial_number, AUTO)


PB_BIND(UBA_PROTO_UBA6_settings, UBA_PROTO_UBA6_settings, AUTO)


PB_BIND(UBA_PROTO_UBA6_info, UBA_PROTO_UBA6_info, AUTO)


PB_BIND(UBA_PROTO_UBA6_status, UBA_PROTO_UBA6_status, AUTO)


PB_BIND(UBA_PROTO_UBA6_command, UBA_PROTO_UBA6_command, AUTO)






