/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_QUERY_UBA_PROTO_QUERY_PB_H_INCLUDED
#define PB_UBA_PROTO_QUERY_UBA_PROTO_QUERY_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_UBA6.pb.h"
#include "UBA_PROTO_LINE.pb.h"
#include "UBA_PROTO_CHANNEL.pb.h"
#include "UBA_PROTO_BPT.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_QUERY_RECIPIENT {
    UBA_PROTO_QUERY_RECIPIENT_NONE = 0,
    UBA_PROTO_QUERY_RECIPIENT_DEVICE = 1,
    UBA_PROTO_QUERY_RECIPIENT_LINE_A = 2,
    UBA_PROTO_QUERY_RECIPIENT_LINE_B = 4,
    UBA_PROTO_QUERY_RECIPIENT_CHANNEL_A = 8,
    UBA_PROTO_QUERY_RECIPIENT_CHANNEL_B = 16,
    UBA_PROTO_QUERY_RECIPIENT_CHANNEL_AB = 32,
    UBA_PROTO_QUERY_RECIPIENT_BPT_A = 64,
    UBA_PROTO_QUERY_RECIPIENT_BPT_B = 128,
    UBA_PROTO_QUERY_RECIPIENT_BPT_AB = 256
} UBA_PROTO_QUERY_RECIPIENT;

/* Struct definitions */
typedef struct _UBA_PROTO_QUERY_query_message {
    UBA_PROTO_QUERY_RECIPIENT recipient;
} UBA_PROTO_QUERY_query_message;

typedef struct _UBA_PROTO_QUERY_query_response_message {
    UBA_PROTO_QUERY_RECIPIENT recipient;
    uint32_t response_id; /* the id of the query message */
    pb_size_t which_status;
    union {
        UBA_PROTO_UBA6_status device;
        UBA_PROTO_LINE_status line;
        UBA_PROTO_CHANNEL_status channel;
        UBA_PROTO_BPT_status_message bpt;
    } status;
} UBA_PROTO_QUERY_query_response_message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_QUERY_RECIPIENT_MIN UBA_PROTO_QUERY_RECIPIENT_NONE
#define _UBA_PROTO_QUERY_RECIPIENT_MAX UBA_PROTO_QUERY_RECIPIENT_BPT_AB
#define _UBA_PROTO_QUERY_RECIPIENT_ARRAYSIZE ((UBA_PROTO_QUERY_RECIPIENT)(UBA_PROTO_QUERY_RECIPIENT_BPT_AB+1))

#define UBA_PROTO_QUERY_query_message_recipient_ENUMTYPE UBA_PROTO_QUERY_RECIPIENT

#define UBA_PROTO_QUERY_query_response_message_recipient_ENUMTYPE UBA_PROTO_QUERY_RECIPIENT


/* Initializer values for message structs */
#define UBA_PROTO_QUERY_query_message_init_default {_UBA_PROTO_QUERY_RECIPIENT_MIN}
#define UBA_PROTO_QUERY_query_response_message_init_default {_UBA_PROTO_QUERY_RECIPIENT_MIN, 0, 0, {UBA_PROTO_UBA6_status_init_default}}
#define UBA_PROTO_QUERY_query_message_init_zero  {_UBA_PROTO_QUERY_RECIPIENT_MIN}
#define UBA_PROTO_QUERY_query_response_message_init_zero {_UBA_PROTO_QUERY_RECIPIENT_MIN, 0, 0, {UBA_PROTO_UBA6_status_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_QUERY_query_message_recipient_tag 1
#define UBA_PROTO_QUERY_query_response_message_recipient_tag 1
#define UBA_PROTO_QUERY_query_response_message_response_id_tag 2
#define UBA_PROTO_QUERY_query_response_message_device_tag 3
#define UBA_PROTO_QUERY_query_response_message_line_tag 4
#define UBA_PROTO_QUERY_query_response_message_channel_tag 5
#define UBA_PROTO_QUERY_query_response_message_bpt_tag 6

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_QUERY_query_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    recipient,         1)
#define UBA_PROTO_QUERY_query_message_CALLBACK NULL
#define UBA_PROTO_QUERY_query_message_DEFAULT NULL

#define UBA_PROTO_QUERY_query_response_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    recipient,         1) \
X(a, STATIC,   SINGULAR, UINT32,   response_id,       2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (status,device,status.device),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (status,line,status.line),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (status,channel,status.channel),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (status,bpt,status.bpt),   6)
#define UBA_PROTO_QUERY_query_response_message_CALLBACK NULL
#define UBA_PROTO_QUERY_query_response_message_DEFAULT NULL
#define UBA_PROTO_QUERY_query_response_message_status_device_MSGTYPE UBA_PROTO_UBA6_status
#define UBA_PROTO_QUERY_query_response_message_status_line_MSGTYPE UBA_PROTO_LINE_status
#define UBA_PROTO_QUERY_query_response_message_status_channel_MSGTYPE UBA_PROTO_CHANNEL_status
#define UBA_PROTO_QUERY_query_response_message_status_bpt_MSGTYPE UBA_PROTO_BPT_status_message

extern const pb_msgdesc_t UBA_PROTO_QUERY_query_message_msg;
extern const pb_msgdesc_t UBA_PROTO_QUERY_query_response_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_QUERY_query_message_fields &UBA_PROTO_QUERY_query_message_msg
#define UBA_PROTO_QUERY_query_response_message_fields &UBA_PROTO_QUERY_query_response_message_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_QUERY_UBA_PROTO_QUERY_PB_H_MAX_SIZE UBA_PROTO_QUERY_query_response_message_size
#define UBA_PROTO_QUERY_query_message_size       3
#define UBA_PROTO_QUERY_query_response_message_size 320

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
