/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_LINE_UBA_PROTO_LINE_PB_H_INCLUDED
#define PB_UBA_PROTO_LINE_UBA_PROTO_LINE_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_UBA6.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_LINE_ID {
    UBA_PROTO_LINE_ID_NONE = 0,
    UBA_PROTO_LINE_ID_A = 1,
    UBA_PROTO_LINE_ID_B = 2
} UBA_PROTO_LINE_ID;

typedef enum _UBA_PROTO_LINE_STATE {
    UBA_PROTO_LINE_STATE_INIT = 0,
    UBA_PROTO_LINE_STATE_IDLE = 1,
    UBA_PROTO_LINE_STATE_PRE_CHARGING = 2,
    UBA_PROTO_LINE_STATE_CHARGING_CC = 3,
    UBA_PROTO_LINE_STATE_CHARGING_CV = 4,
    UBA_PROTO_LINE_STATE_DISCHARGING = 5,
    UBA_PROTO_LINE_STATE_DEAD = 6
} UBA_PROTO_LINE_STATE;

typedef enum _UBA_PROTO_LINE_CMD_ID {
    UBA_PROTO_LINE_CMD_ID_TEST = 0, /* do nothing */
    UBA_PROTO_LINE_CMD_ID_CALIBRATION = 1, /* disable/enable calibration */
    UBA_PROTO_LINE_CMD_ID_CHARGE_ENABLE = 2, /* tuen on/off the charge enable */
    UBA_PROTO_LINE_CMD_ID_DISCHARGE_ENABLE = 3, /* tuen on/off the discharge enable */
    UBA_PROTO_LINE_CMD_ID_TARGET = 4, /* set the target Voltage and current and set new state */
    UBA_PROTO_LINE_CMD_ID_BIST = 5 /* start built in self test */
} UBA_PROTO_LINE_CMD_ID;

/* Struct definitions */
typedef struct _UBA_PROTO_LINE_data_message {
    int32_t voltage;
    int32_t gen_voltage;
    float bat_temperature;
    float amb_temperature;
    int32_t discharge_current;
    int32_t charge_current;
    int32_t vps;
    float capacity;
    bool isBattery_connected;
} UBA_PROTO_LINE_data_message;

typedef struct _UBA_PROTO_LINE_adc_data_message {
    uint16_t vbat;
    uint16_t vgen;
    uint16_t amb_temp;
    uint16_t ntc_temp;
    uint16_t discharge_curr;
    uint16_t charge_curr;
    uint16_t vps;
} UBA_PROTO_LINE_adc_data_message;

typedef struct _UBA_PROTO_LINE_status {
    UBA_PROTO_LINE_ID id;
    UBA_PROTO_LINE_STATE state;
    UBA_PROTO_UBA6_ERROR error;
    UBA_PROTO_LINE_data_message data;
    bool has_adc_data;
    UBA_PROTO_LINE_adc_data_message adc_data;
} UBA_PROTO_LINE_status;

typedef struct _UBA_PROTO_LINE_command {
    UBA_PROTO_LINE_CMD_ID id;
    UBA_PROTO_LINE_ID line_id; /* the selected line (A/B) */
    uint8_t state; /* on/off /UBA_PROTO_LINE.state */
    int32_t current; /* target current */
    int32_t voltage; /* target current */
} UBA_PROTO_LINE_command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_LINE_ID_MIN UBA_PROTO_LINE_ID_NONE
#define _UBA_PROTO_LINE_ID_MAX UBA_PROTO_LINE_ID_B
#define _UBA_PROTO_LINE_ID_ARRAYSIZE ((UBA_PROTO_LINE_ID)(UBA_PROTO_LINE_ID_B+1))

#define _UBA_PROTO_LINE_STATE_MIN UBA_PROTO_LINE_STATE_INIT
#define _UBA_PROTO_LINE_STATE_MAX UBA_PROTO_LINE_STATE_DEAD
#define _UBA_PROTO_LINE_STATE_ARRAYSIZE ((UBA_PROTO_LINE_STATE)(UBA_PROTO_LINE_STATE_DEAD+1))

#define _UBA_PROTO_LINE_CMD_ID_MIN UBA_PROTO_LINE_CMD_ID_TEST
#define _UBA_PROTO_LINE_CMD_ID_MAX UBA_PROTO_LINE_CMD_ID_BIST
#define _UBA_PROTO_LINE_CMD_ID_ARRAYSIZE ((UBA_PROTO_LINE_CMD_ID)(UBA_PROTO_LINE_CMD_ID_BIST+1))



#define UBA_PROTO_LINE_status_id_ENUMTYPE UBA_PROTO_LINE_ID
#define UBA_PROTO_LINE_status_state_ENUMTYPE UBA_PROTO_LINE_STATE
#define UBA_PROTO_LINE_status_error_ENUMTYPE UBA_PROTO_UBA6_ERROR

#define UBA_PROTO_LINE_command_id_ENUMTYPE UBA_PROTO_LINE_CMD_ID
#define UBA_PROTO_LINE_command_line_id_ENUMTYPE UBA_PROTO_LINE_ID


/* Initializer values for message structs */
#define UBA_PROTO_LINE_data_message_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define UBA_PROTO_LINE_adc_data_message_init_default {0, 0, 0, 0, 0, 0, 0}
#define UBA_PROTO_LINE_status_init_default       {_UBA_PROTO_LINE_ID_MIN, _UBA_PROTO_LINE_STATE_MIN, _UBA_PROTO_UBA6_ERROR_MIN, UBA_PROTO_LINE_data_message_init_default, false, UBA_PROTO_LINE_adc_data_message_init_default}
#define UBA_PROTO_LINE_command_init_default      {_UBA_PROTO_LINE_CMD_ID_MIN, _UBA_PROTO_LINE_ID_MIN, 0, 0, 0}
#define UBA_PROTO_LINE_data_message_init_zero    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define UBA_PROTO_LINE_adc_data_message_init_zero {0, 0, 0, 0, 0, 0, 0}
#define UBA_PROTO_LINE_status_init_zero          {_UBA_PROTO_LINE_ID_MIN, _UBA_PROTO_LINE_STATE_MIN, _UBA_PROTO_UBA6_ERROR_MIN, UBA_PROTO_LINE_data_message_init_zero, false, UBA_PROTO_LINE_adc_data_message_init_zero}
#define UBA_PROTO_LINE_command_init_zero         {_UBA_PROTO_LINE_CMD_ID_MIN, _UBA_PROTO_LINE_ID_MIN, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_LINE_data_message_voltage_tag  1
#define UBA_PROTO_LINE_data_message_gen_voltage_tag 2
#define UBA_PROTO_LINE_data_message_bat_temperature_tag 3
#define UBA_PROTO_LINE_data_message_amb_temperature_tag 4
#define UBA_PROTO_LINE_data_message_discharge_current_tag 5
#define UBA_PROTO_LINE_data_message_charge_current_tag 6
#define UBA_PROTO_LINE_data_message_vps_tag      7
#define UBA_PROTO_LINE_data_message_capacity_tag 8
#define UBA_PROTO_LINE_data_message_isBattery_connected_tag 9
#define UBA_PROTO_LINE_adc_data_message_vbat_tag 1
#define UBA_PROTO_LINE_adc_data_message_vgen_tag 2
#define UBA_PROTO_LINE_adc_data_message_amb_temp_tag 3
#define UBA_PROTO_LINE_adc_data_message_ntc_temp_tag 4
#define UBA_PROTO_LINE_adc_data_message_discharge_curr_tag 5
#define UBA_PROTO_LINE_adc_data_message_charge_curr_tag 6
#define UBA_PROTO_LINE_adc_data_message_vps_tag  7
#define UBA_PROTO_LINE_status_id_tag             1
#define UBA_PROTO_LINE_status_state_tag          2
#define UBA_PROTO_LINE_status_error_tag          3
#define UBA_PROTO_LINE_status_data_tag           4
#define UBA_PROTO_LINE_status_adc_data_tag       5
#define UBA_PROTO_LINE_command_id_tag            1
#define UBA_PROTO_LINE_command_line_id_tag       2
#define UBA_PROTO_LINE_command_state_tag         3
#define UBA_PROTO_LINE_command_current_tag       4
#define UBA_PROTO_LINE_command_voltage_tag       5

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_LINE_data_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           1) \
X(a, STATIC,   SINGULAR, INT32,    gen_voltage,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    bat_temperature,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    amb_temperature,   4) \
X(a, STATIC,   SINGULAR, INT32,    discharge_current,   5) \
X(a, STATIC,   SINGULAR, INT32,    charge_current,    6) \
X(a, STATIC,   SINGULAR, INT32,    vps,               7) \
X(a, STATIC,   SINGULAR, FLOAT,    capacity,          8) \
X(a, STATIC,   SINGULAR, BOOL,     isBattery_connected,   9)
#define UBA_PROTO_LINE_data_message_CALLBACK NULL
#define UBA_PROTO_LINE_data_message_DEFAULT NULL

#define UBA_PROTO_LINE_adc_data_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   vbat,              1) \
X(a, STATIC,   SINGULAR, UINT32,   vgen,              2) \
X(a, STATIC,   SINGULAR, UINT32,   amb_temp,          3) \
X(a, STATIC,   SINGULAR, UINT32,   ntc_temp,          4) \
X(a, STATIC,   SINGULAR, UINT32,   discharge_curr,    5) \
X(a, STATIC,   SINGULAR, UINT32,   charge_curr,       6) \
X(a, STATIC,   SINGULAR, UINT32,   vps,               7)
#define UBA_PROTO_LINE_adc_data_message_CALLBACK NULL
#define UBA_PROTO_LINE_adc_data_message_DEFAULT NULL

#define UBA_PROTO_LINE_status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UENUM,    error,             3) \
X(a, STATIC,   SINGULAR, MESSAGE,  data,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  adc_data,          5)
#define UBA_PROTO_LINE_status_CALLBACK NULL
#define UBA_PROTO_LINE_status_DEFAULT NULL
#define UBA_PROTO_LINE_status_data_MSGTYPE UBA_PROTO_LINE_data_message
#define UBA_PROTO_LINE_status_adc_data_MSGTYPE UBA_PROTO_LINE_adc_data_message

#define UBA_PROTO_LINE_command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    line_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   state,             3) \
X(a, STATIC,   SINGULAR, INT32,    current,           4) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           5)
#define UBA_PROTO_LINE_command_CALLBACK NULL
#define UBA_PROTO_LINE_command_DEFAULT NULL

extern const pb_msgdesc_t UBA_PROTO_LINE_data_message_msg;
extern const pb_msgdesc_t UBA_PROTO_LINE_adc_data_message_msg;
extern const pb_msgdesc_t UBA_PROTO_LINE_status_msg;
extern const pb_msgdesc_t UBA_PROTO_LINE_command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_LINE_data_message_fields &UBA_PROTO_LINE_data_message_msg
#define UBA_PROTO_LINE_adc_data_message_fields &UBA_PROTO_LINE_adc_data_message_msg
#define UBA_PROTO_LINE_status_fields &UBA_PROTO_LINE_status_msg
#define UBA_PROTO_LINE_command_fields &UBA_PROTO_LINE_command_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_LINE_UBA_PROTO_LINE_PB_H_MAX_SIZE UBA_PROTO_LINE_status_size
#define UBA_PROTO_LINE_adc_data_message_size     28
#define UBA_PROTO_LINE_command_size              29
#define UBA_PROTO_LINE_data_message_size         72
#define UBA_PROTO_LINE_status_size               114

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
