/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_FM.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UBA_PROTO_FM_command, UBA_PROTO_FM_command, AUTO)


PB_BIND(UBA_PROTO_FM_file_transfer, UBA_PROTO_FM_file_transfer, 2)


PB_BIND(UBA_PROTO_FM_file_list, UBA_PROTO_FM_file_list, 2)


PB_BIND(UBA_PROTO_FM_transfer, UBA_PROTO_FM_transfer, 2)




