/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_FM_UBA_PROTO_FM_PB_H_INCLUDED
#define PB_UBA_PROTO_FM_UBA_PROTO_FM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_FM_CMD_ID {
    UBA_PROTO_FM_CMD_ID_TEST = 0,
    UBA_PROTO_FM_CMD_ID_CHUNK_REQUEST = 1, /* request a chunk of the file */
    UBA_PROTO_FM_CMD_ID_FILE_LIST_REQUEST = 2, /* request the list of the files */
    UBA_PROTO_FM_CMD_ID_BPT_FILE = 3 /* request the file name of the the runnig BPT */
} UBA_PROTO_FM_CMD_ID;

/* Struct definitions */
typedef struct _UBA_PROTO_FM_command {
    UBA_PROTO_FM_CMD_ID id;
    char filename[64]; /* the name of the file */
    uint32_t chunk_index; /* the requested chank or the channle index */
} UBA_PROTO_FM_command;

typedef PB_BYTES_ARRAY_T(2048) UBA_PROTO_FM_file_transfer_data_t;
typedef struct _UBA_PROTO_FM_file_transfer {
    char filename[64]; /* the name of the file */
    uint32_t total_size;
    uint32_t chunk_size;
    uint32_t chunk_index;
    UBA_PROTO_FM_file_transfer_data_t data;
} UBA_PROTO_FM_file_transfer;

typedef struct _UBA_PROTO_FM_file_list {
    pb_size_t filenames_count;
    char filenames[20][64];
    uint16_t total_files; /* the total number of files on the device */
} UBA_PROTO_FM_file_list;

typedef struct _UBA_PROTO_FM_transfer {
    pb_size_t which_request;
    union {
        UBA_PROTO_FM_file_list list;
        UBA_PROTO_FM_file_transfer file;
    } request;
} UBA_PROTO_FM_transfer;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_FM_CMD_ID_MIN UBA_PROTO_FM_CMD_ID_TEST
#define _UBA_PROTO_FM_CMD_ID_MAX UBA_PROTO_FM_CMD_ID_BPT_FILE
#define _UBA_PROTO_FM_CMD_ID_ARRAYSIZE ((UBA_PROTO_FM_CMD_ID)(UBA_PROTO_FM_CMD_ID_BPT_FILE+1))

#define UBA_PROTO_FM_command_id_ENUMTYPE UBA_PROTO_FM_CMD_ID





/* Initializer values for message structs */
#define UBA_PROTO_FM_command_init_default        {_UBA_PROTO_FM_CMD_ID_MIN, "", 0}
#define UBA_PROTO_FM_file_transfer_init_default  {"", 0, 0, 0, {0, {0}}}
#define UBA_PROTO_FM_file_list_init_default      {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0}
#define UBA_PROTO_FM_transfer_init_default       {0, {UBA_PROTO_FM_file_list_init_default}}
#define UBA_PROTO_FM_command_init_zero           {_UBA_PROTO_FM_CMD_ID_MIN, "", 0}
#define UBA_PROTO_FM_file_transfer_init_zero     {"", 0, 0, 0, {0, {0}}}
#define UBA_PROTO_FM_file_list_init_zero         {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0}
#define UBA_PROTO_FM_transfer_init_zero          {0, {UBA_PROTO_FM_file_list_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_FM_command_id_tag              1
#define UBA_PROTO_FM_command_filename_tag        2
#define UBA_PROTO_FM_command_chunk_index_tag     3
#define UBA_PROTO_FM_file_transfer_filename_tag  1
#define UBA_PROTO_FM_file_transfer_total_size_tag 2
#define UBA_PROTO_FM_file_transfer_chunk_size_tag 3
#define UBA_PROTO_FM_file_transfer_chunk_index_tag 4
#define UBA_PROTO_FM_file_transfer_data_tag      5
#define UBA_PROTO_FM_file_list_filenames_tag     1
#define UBA_PROTO_FM_file_list_total_files_tag   2
#define UBA_PROTO_FM_transfer_list_tag           1
#define UBA_PROTO_FM_transfer_file_tag           2

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_FM_command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, STRING,   filename,          2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       3)
#define UBA_PROTO_FM_command_CALLBACK NULL
#define UBA_PROTO_FM_command_DEFAULT NULL

#define UBA_PROTO_FM_file_transfer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   filename,          1) \
X(a, STATIC,   SINGULAR, UINT32,   total_size,        2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        3) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       4) \
X(a, STATIC,   SINGULAR, BYTES,    data,              5)
#define UBA_PROTO_FM_file_transfer_CALLBACK NULL
#define UBA_PROTO_FM_file_transfer_DEFAULT NULL

#define UBA_PROTO_FM_file_list_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   filenames,         1) \
X(a, STATIC,   SINGULAR, UINT32,   total_files,       2)
#define UBA_PROTO_FM_file_list_CALLBACK NULL
#define UBA_PROTO_FM_file_list_DEFAULT NULL

#define UBA_PROTO_FM_transfer_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list,request.list),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,file,request.file),   2)
#define UBA_PROTO_FM_transfer_CALLBACK NULL
#define UBA_PROTO_FM_transfer_DEFAULT NULL
#define UBA_PROTO_FM_transfer_request_list_MSGTYPE UBA_PROTO_FM_file_list
#define UBA_PROTO_FM_transfer_request_file_MSGTYPE UBA_PROTO_FM_file_transfer

extern const pb_msgdesc_t UBA_PROTO_FM_command_msg;
extern const pb_msgdesc_t UBA_PROTO_FM_file_transfer_msg;
extern const pb_msgdesc_t UBA_PROTO_FM_file_list_msg;
extern const pb_msgdesc_t UBA_PROTO_FM_transfer_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_FM_command_fields &UBA_PROTO_FM_command_msg
#define UBA_PROTO_FM_file_transfer_fields &UBA_PROTO_FM_file_transfer_msg
#define UBA_PROTO_FM_file_list_fields &UBA_PROTO_FM_file_list_msg
#define UBA_PROTO_FM_transfer_fields &UBA_PROTO_FM_transfer_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_FM_UBA_PROTO_FM_PB_H_MAX_SIZE  UBA_PROTO_FM_transfer_size
#define UBA_PROTO_FM_command_size                73
#define UBA_PROTO_FM_file_list_size              1304
#define UBA_PROTO_FM_file_transfer_size          2134
#define UBA_PROTO_FM_transfer_size               2137

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
