/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_CMD_UBA_PROTO_CMD_PB_H_INCLUDED
#define PB_UBA_PROTO_CMD_UBA_PROTO_CMD_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_UBA6.pb.h"
#include "UBA_PROTO_CHANNEL.pb.h"
#include "UBA_PROTO_LINE.pb.h"
#include "UBA_PROTO_BPT.pb.h"
#include "UBA_PROTO_FM.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UBA_PROTO_CMD_command_message {
    pb_size_t which_command;
    union {
        UBA_PROTO_LINE_command line;
        UBA_PROTO_CHANNEL_command channel;
        UBA_PROTO_UBA6_command uba;
        UBA_PROTO_BPT_command bpt;
        UBA_PROTO_FM_command file;
    } command;
} UBA_PROTO_CMD_command_message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UBA_PROTO_CMD_command_message_init_default {0, {UBA_PROTO_LINE_command_init_default}}
#define UBA_PROTO_CMD_command_message_init_zero  {0, {UBA_PROTO_LINE_command_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_CMD_command_message_line_tag   1
#define UBA_PROTO_CMD_command_message_channel_tag 2
#define UBA_PROTO_CMD_command_message_uba_tag    3
#define UBA_PROTO_CMD_command_message_bpt_tag    4
#define UBA_PROTO_CMD_command_message_file_tag   5

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_CMD_command_message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,line,command.line),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,channel,command.channel),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,uba,command.uba),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,bpt,command.bpt),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,file,command.file),   5)
#define UBA_PROTO_CMD_command_message_CALLBACK NULL
#define UBA_PROTO_CMD_command_message_DEFAULT NULL
#define UBA_PROTO_CMD_command_message_command_line_MSGTYPE UBA_PROTO_LINE_command
#define UBA_PROTO_CMD_command_message_command_channel_MSGTYPE UBA_PROTO_CHANNEL_command
#define UBA_PROTO_CMD_command_message_command_uba_MSGTYPE UBA_PROTO_UBA6_command
#define UBA_PROTO_CMD_command_message_command_bpt_MSGTYPE UBA_PROTO_BPT_command
#define UBA_PROTO_CMD_command_message_command_file_MSGTYPE UBA_PROTO_FM_command

extern const pb_msgdesc_t UBA_PROTO_CMD_command_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_CMD_command_message_fields &UBA_PROTO_CMD_command_message_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_CMD_UBA_PROTO_CMD_PB_H_MAX_SIZE UBA_PROTO_CMD_command_message_size
#define UBA_PROTO_CMD_command_message_size       75

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
