/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_BPT.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UBA_PROTO_BPT_discharge_current, UBA_PROTO_BPT_discharge_current, AUTO)


PB_BIND(UBA_PROTO_BPT_charge_stop_condition, UBA_PROTO_BPT_charge_stop_condition, AUTO)


PB_BIND(UBA_PROTO_BPT_charge, UBA_PROTO_BPT_charge, AUTO)


PB_BIND(UBA_PROTO_BPT_discharge_stop_condition, UBA_PROTO_BPT_discharge_stop_condition, AUTO)


PB_BIND(UBA_PROTO_BPT_discharge, UBA_PROTO_BPT_discharge, AUTO)


PB_BIND(UBA_PROTO_BPT_delay, UBA_PROTO_BPT_delay, AUTO)


PB_BIND(UBA_PROTO_BPT_BPT, UBA_PROTO_BPT_BPT, AUTO)


PB_BIND(UBA_PROTO_BPT_data_log_message, UBA_PROTO_BPT_data_log_message, AUTO)


PB_BIND(UBA_PROTO_BPT_command, UBA_PROTO_BPT_command, AUTO)


PB_BIND(UBA_PROTO_BPT_status_message, UBA_PROTO_BPT_status_message, AUTO)









