/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_CHANNEL_UBA_PROTO_CHANNEL_PB_H_INCLUDED
#define PB_UBA_PROTO_CHANNEL_UBA_PROTO_CHANNEL_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_LINE.pb.h"
#include "UBA_PROTO_UBA6.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UBA_PROTO_CHANNEL_ID {
    UBA_PROTO_CHANNEL_ID_NONE = 0,
    UBA_PROTO_CHANNEL_ID_A = 1,
    UBA_PROTO_CHANNEL_ID_B = 2,
    UBA_PROTO_CHANNEL_ID_AB = 3
} UBA_PROTO_CHANNEL_ID;

typedef enum _UBA_PROTO_CHANNEL_STATE {
    UBA_PROTO_CHANNEL_STATE_INIT = 0, /* configure the channel */
    UBA_PROTO_CHANNEL_STATE_STANDBY = 1, /* wait for external state change , make sure that the channel is in idle mode all the time */
    UBA_PROTO_CHANNEL_STATE_DELAY = 2,
    UBA_PROTO_CHANNEL_STATE_CHARGE = 3,
    UBA_PROTO_CHANNEL_STATE_DISCHARGE = 4,
    UBA_PROTO_CHANNEL_STATE_OFF = 5
} UBA_PROTO_CHANNEL_STATE;

typedef enum _UBA_PROTO_CHANNEL_CMD_ID {
    UBA_PROTO_CHANNEL_CMD_ID_TEST = 0,
    UBA_PROTO_CHANNEL_CMD_ID_DCDC = 1 /* set the state and value of the DC to DC Converter */
} UBA_PROTO_CHANNEL_CMD_ID;

/* Struct definitions */
typedef struct _UBA_PROTO_CHANNEL_data_message {
    int32_t voltage;
    float temperature;
    int32_t current;
    float capacity;
    bool isBattery_connected;
} UBA_PROTO_CHANNEL_data_message;

typedef struct _UBA_PROTO_CHANNEL_status {
    uint8_t state; /* the state of the channel */
    uint8_t id; /* the id of the channel (A/B/AB) */
    uint8_t size; /* the number of the lines in the channnel */
    bool has_data;
    UBA_PROTO_CHANNEL_data_message data; /* that data of the cheannle */
    UBA_PROTO_LINE_status line_status[2];
    UBA_PROTO_UBA6_ERROR error;
} UBA_PROTO_CHANNEL_status;

typedef struct _UBA_PROTO_CHANNEL_command {
    UBA_PROTO_CHANNEL_CMD_ID id;
    UBA_PROTO_CHANNEL_ID channel;
} UBA_PROTO_CHANNEL_command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UBA_PROTO_CHANNEL_ID_MIN UBA_PROTO_CHANNEL_ID_NONE
#define _UBA_PROTO_CHANNEL_ID_MAX UBA_PROTO_CHANNEL_ID_AB
#define _UBA_PROTO_CHANNEL_ID_ARRAYSIZE ((UBA_PROTO_CHANNEL_ID)(UBA_PROTO_CHANNEL_ID_AB+1))

#define _UBA_PROTO_CHANNEL_STATE_MIN UBA_PROTO_CHANNEL_STATE_INIT
#define _UBA_PROTO_CHANNEL_STATE_MAX UBA_PROTO_CHANNEL_STATE_OFF
#define _UBA_PROTO_CHANNEL_STATE_ARRAYSIZE ((UBA_PROTO_CHANNEL_STATE)(UBA_PROTO_CHANNEL_STATE_OFF+1))

#define _UBA_PROTO_CHANNEL_CMD_ID_MIN UBA_PROTO_CHANNEL_CMD_ID_TEST
#define _UBA_PROTO_CHANNEL_CMD_ID_MAX UBA_PROTO_CHANNEL_CMD_ID_DCDC
#define _UBA_PROTO_CHANNEL_CMD_ID_ARRAYSIZE ((UBA_PROTO_CHANNEL_CMD_ID)(UBA_PROTO_CHANNEL_CMD_ID_DCDC+1))


#define UBA_PROTO_CHANNEL_status_error_ENUMTYPE UBA_PROTO_UBA6_ERROR

#define UBA_PROTO_CHANNEL_command_id_ENUMTYPE UBA_PROTO_CHANNEL_CMD_ID
#define UBA_PROTO_CHANNEL_command_channel_ENUMTYPE UBA_PROTO_CHANNEL_ID


/* Initializer values for message structs */
#define UBA_PROTO_CHANNEL_data_message_init_default {0, 0, 0, 0, 0}
#define UBA_PROTO_CHANNEL_status_init_default    {0, 0, 0, false, UBA_PROTO_CHANNEL_data_message_init_default, {UBA_PROTO_LINE_status_init_default, UBA_PROTO_LINE_status_init_default}, _UBA_PROTO_UBA6_ERROR_MIN}
#define UBA_PROTO_CHANNEL_command_init_default   {_UBA_PROTO_CHANNEL_CMD_ID_MIN, _UBA_PROTO_CHANNEL_ID_MIN}
#define UBA_PROTO_CHANNEL_data_message_init_zero {0, 0, 0, 0, 0}
#define UBA_PROTO_CHANNEL_status_init_zero       {0, 0, 0, false, UBA_PROTO_CHANNEL_data_message_init_zero, {UBA_PROTO_LINE_status_init_zero, UBA_PROTO_LINE_status_init_zero}, _UBA_PROTO_UBA6_ERROR_MIN}
#define UBA_PROTO_CHANNEL_command_init_zero      {_UBA_PROTO_CHANNEL_CMD_ID_MIN, _UBA_PROTO_CHANNEL_ID_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_CHANNEL_data_message_voltage_tag 1
#define UBA_PROTO_CHANNEL_data_message_temperature_tag 2
#define UBA_PROTO_CHANNEL_data_message_current_tag 3
#define UBA_PROTO_CHANNEL_data_message_capacity_tag 4
#define UBA_PROTO_CHANNEL_data_message_isBattery_connected_tag 5
#define UBA_PROTO_CHANNEL_status_state_tag       1
#define UBA_PROTO_CHANNEL_status_id_tag          2
#define UBA_PROTO_CHANNEL_status_size_tag        3
#define UBA_PROTO_CHANNEL_status_data_tag        4
#define UBA_PROTO_CHANNEL_status_line_status_tag 5
#define UBA_PROTO_CHANNEL_status_error_tag       6
#define UBA_PROTO_CHANNEL_command_id_tag         1
#define UBA_PROTO_CHANNEL_command_channel_tag    2

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_CHANNEL_data_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    voltage,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, INT32,    current,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    capacity,          4) \
X(a, STATIC,   SINGULAR, BOOL,     isBattery_connected,   5)
#define UBA_PROTO_CHANNEL_data_message_CALLBACK NULL
#define UBA_PROTO_CHANNEL_data_message_DEFAULT NULL

#define UBA_PROTO_CHANNEL_status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2) \
X(a, STATIC,   SINGULAR, UINT32,   size,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              4) \
X(a, STATIC,   FIXARRAY, MESSAGE,  line_status,       5) \
X(a, STATIC,   SINGULAR, UENUM,    error,             6)
#define UBA_PROTO_CHANNEL_status_CALLBACK NULL
#define UBA_PROTO_CHANNEL_status_DEFAULT NULL
#define UBA_PROTO_CHANNEL_status_data_MSGTYPE UBA_PROTO_CHANNEL_data_message
#define UBA_PROTO_CHANNEL_status_line_status_MSGTYPE UBA_PROTO_LINE_status

#define UBA_PROTO_CHANNEL_command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    channel,           2)
#define UBA_PROTO_CHANNEL_command_CALLBACK NULL
#define UBA_PROTO_CHANNEL_command_DEFAULT NULL

extern const pb_msgdesc_t UBA_PROTO_CHANNEL_data_message_msg;
extern const pb_msgdesc_t UBA_PROTO_CHANNEL_status_msg;
extern const pb_msgdesc_t UBA_PROTO_CHANNEL_command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_CHANNEL_data_message_fields &UBA_PROTO_CHANNEL_data_message_msg
#define UBA_PROTO_CHANNEL_status_fields &UBA_PROTO_CHANNEL_status_msg
#define UBA_PROTO_CHANNEL_command_fields &UBA_PROTO_CHANNEL_command_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_CHANNEL_UBA_PROTO_CHANNEL_PB_H_MAX_SIZE UBA_PROTO_CHANNEL_status_size
#define UBA_PROTO_CHANNEL_command_size           4
#define UBA_PROTO_CHANNEL_data_message_size      34
#define UBA_PROTO_CHANNEL_status_size            283

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
