/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CHANNLE_UBA_CHANNEL_PB_H_INCLUDED
#define PB_CHANNLE_UBA_CHANNEL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CHANNLE_UBA_CHANNEL_ID {
    CHANNLE_UBA_CHANNEL_ID_NONE = 0,
    CHANNLE_UBA_CHANNEL_ID_A = 1,
    CHANNLE_UBA_CHANNEL_ID_B = 2,
    CHANNLE_UBA_CHANNEL_ID_AB = 3
} CHANNLE_UBA_CHANNEL_ID;

typedef enum _CHANNLE_UBA_CHANNEL_STATE {
    CHANNLE_UBA_CHANNEL_STATE_INIT = 0, /* configure the channel */
    CHANNLE_UBA_CHANNEL_STATE_STANDBY = 1, /* wait for external state change , make sure that the channel is in idle mode all the time */
    CHANNLE_UBA_CHANNEL_STATE_DELAY = 2,
    CHANNLE_UBA_CHANNEL_STATE_CHARGE = 3,
    CHANNLE_UBA_CHANNEL_STATE_DISCHARGE = 4,
    CHANNLE_UBA_CHANNEL_STATE_OFF = 5
} CHANNLE_UBA_CHANNEL_STATE;

/* Struct definitions */
typedef struct _CHANNLE_channel_status {
    uint8_t state;
    uint8_t id;
} CHANNLE_channel_status;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CHANNLE_UBA_CHANNEL_ID_MIN CHANNLE_UBA_CHANNEL_ID_NONE
#define _CHANNLE_UBA_CHANNEL_ID_MAX CHANNLE_UBA_CHANNEL_ID_AB
#define _CHANNLE_UBA_CHANNEL_ID_ARRAYSIZE ((CHANNLE_UBA_CHANNEL_ID)(CHANNLE_UBA_CHANNEL_ID_AB+1))

#define _CHANNLE_UBA_CHANNEL_STATE_MIN CHANNLE_UBA_CHANNEL_STATE_INIT
#define _CHANNLE_UBA_CHANNEL_STATE_MAX CHANNLE_UBA_CHANNEL_STATE_OFF
#define _CHANNLE_UBA_CHANNEL_STATE_ARRAYSIZE ((CHANNLE_UBA_CHANNEL_STATE)(CHANNLE_UBA_CHANNEL_STATE_OFF+1))



/* Initializer values for message structs */
#define CHANNLE_channel_status_init_default      {0, 0}
#define CHANNLE_channel_status_init_zero         {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define CHANNLE_channel_status_state_tag         1
#define CHANNLE_channel_status_id_tag            2

/* Struct field encoding specification for nanopb */
#define CHANNLE_channel_status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2)
#define CHANNLE_channel_status_CALLBACK NULL
#define CHANNLE_channel_status_DEFAULT NULL

extern const pb_msgdesc_t CHANNLE_channel_status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CHANNLE_channel_status_fields &CHANNLE_channel_status_msg

/* Maximum encoded size of messages (where known) */
#define CHANNLE_UBA_CHANNEL_PB_H_MAX_SIZE        CHANNLE_channel_status_size
#define CHANNLE_channel_status_size              6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
