/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MSG_UBA_MESSAGE_PB_H_INCLUDED
#define PB_MSG_UBA_MESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_CMD.pb.h"
#include "UBA_PROTO_TR.pb.h"
#include "UBA_PROTO_CHANNEL.pb.h"
#include "UBA_PROTO_CALIBRATION.pb.h"
#include "UBA_PROTO_QUERY.pb.h"
#include "UBA_PROTO_UBA6.pb.h"
#include "UBA_PROTO_LINE.pb.h"
#include "UBA_PROTO_BPT.pb.h"
#include "UBA_PROTO_FM.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MSG_Header {
    uint32_t sender_address;
    uint32_t target_address;
    uint32_t length;
    uint32_t id;
} MSG_Header;

typedef struct _MSG_Message {
    MSG_Header head;
    pb_size_t which_pyload;
    union {
        UBA_PROTO_CMD_command_message cmd;
        TR_Test_Routine_Message tr; /* sennd/recive a test rotine */
        UBA_PROTO_QUERY_query_message query;
        UBA_PROTO_QUERY_query_response_message query_response;
        UBA_PROTO_CALIBRATION_calibration_message calibration;
        UBA_PROTO_UBA6_status device;
        UBA_PROTO_LINE_status line_status;
        UBA_PROTO_CHANNEL_status channel_status;
        UBA_PROTO_BPT_status_message bpt_status;
        UBA_PROTO_UBA6_settings device_settings;
        UBA_PROTO_FM_file_transfer file;
        UBA_PROTO_FM_file_list fm_list;
    } pyload;
} MSG_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MSG_Header_init_default                  {0, 0, 0, 0}
#define MSG_Message_init_default                 {MSG_Header_init_default, 0, {UBA_PROTO_CMD_command_message_init_default}}
#define MSG_Header_init_zero                     {0, 0, 0, 0}
#define MSG_Message_init_zero                    {MSG_Header_init_zero, 0, {UBA_PROTO_CMD_command_message_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MSG_Header_sender_address_tag            1
#define MSG_Header_target_address_tag            2
#define MSG_Header_length_tag                    3
#define MSG_Header_id_tag                        4
#define MSG_Message_head_tag                     1
#define MSG_Message_cmd_tag                      2
#define MSG_Message_tr_tag                       3
#define MSG_Message_query_tag                    4
#define MSG_Message_query_response_tag           5
#define MSG_Message_calibration_tag              6
#define MSG_Message_device_tag                   7
#define MSG_Message_line_status_tag              8
#define MSG_Message_channel_status_tag           9
#define MSG_Message_bpt_status_tag               10
#define MSG_Message_device_settings_tag          11
#define MSG_Message_file_tag                     12
#define MSG_Message_fm_list_tag                  13

/* Struct field encoding specification for nanopb */
#define MSG_Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sender_address,    1) \
X(a, STATIC,   SINGULAR, UINT32,   target_address,    2) \
X(a, STATIC,   SINGULAR, UINT32,   length,            3) \
X(a, STATIC,   SINGULAR, UINT32,   id,                4)
#define MSG_Header_CALLBACK NULL
#define MSG_Header_DEFAULT NULL

#define MSG_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  head,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,cmd,pyload.cmd),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,tr,pyload.tr),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,query,pyload.query),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,query_response,pyload.query_response),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,calibration,pyload.calibration),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,device,pyload.device),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,line_status,pyload.line_status),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,channel_status,pyload.channel_status),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,bpt_status,pyload.bpt_status),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,device_settings,pyload.device_settings),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,file,pyload.file),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (pyload,fm_list,pyload.fm_list),  13)
#define MSG_Message_CALLBACK NULL
#define MSG_Message_DEFAULT NULL
#define MSG_Message_head_MSGTYPE MSG_Header
#define MSG_Message_pyload_cmd_MSGTYPE UBA_PROTO_CMD_command_message
#define MSG_Message_pyload_tr_MSGTYPE TR_Test_Routine_Message
#define MSG_Message_pyload_query_MSGTYPE UBA_PROTO_QUERY_query_message
#define MSG_Message_pyload_query_response_MSGTYPE UBA_PROTO_QUERY_query_response_message
#define MSG_Message_pyload_calibration_MSGTYPE UBA_PROTO_CALIBRATION_calibration_message
#define MSG_Message_pyload_device_MSGTYPE UBA_PROTO_UBA6_status
#define MSG_Message_pyload_line_status_MSGTYPE UBA_PROTO_LINE_status
#define MSG_Message_pyload_channel_status_MSGTYPE UBA_PROTO_CHANNEL_status
#define MSG_Message_pyload_bpt_status_MSGTYPE UBA_PROTO_BPT_status_message
#define MSG_Message_pyload_device_settings_MSGTYPE UBA_PROTO_UBA6_settings
#define MSG_Message_pyload_file_MSGTYPE UBA_PROTO_FM_file_transfer
#define MSG_Message_pyload_fm_list_MSGTYPE UBA_PROTO_FM_file_list

extern const pb_msgdesc_t MSG_Header_msg;
extern const pb_msgdesc_t MSG_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MSG_Header_fields &MSG_Header_msg
#define MSG_Message_fields &MSG_Message_msg

/* Maximum encoded size of messages (where known) */
#define MSG_Header_size                          24
#define MSG_Message_size                         2163
#define MSG_UBA_MESSAGE_PB_H_MAX_SIZE            MSG_Message_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
