/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_CALIBRATION_UBA_PROTO_CALIBRATION_PB_H_INCLUDED
#define PB_UBA_PROTO_CALIBRATION_UBA_PROTO_CALIBRATION_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_LINE.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UBA_PROTO_CALIBRATION_liniar_calibration_message {
    float slop;
    float y_intercept;
} UBA_PROTO_CALIBRATION_liniar_calibration_message;

typedef struct _UBA_PROTO_CALIBRATION_line_calibration_message {
    UBA_PROTO_LINE_ID id;
    UBA_PROTO_CALIBRATION_liniar_calibration_message vbat[3];
    UBA_PROTO_CALIBRATION_liniar_calibration_message vgen;
    UBA_PROTO_CALIBRATION_liniar_calibration_message vps;
    UBA_PROTO_CALIBRATION_liniar_calibration_message charge_current;
    UBA_PROTO_CALIBRATION_liniar_calibration_message discharge_current;
    UBA_PROTO_CALIBRATION_liniar_calibration_message amb_temp;
    UBA_PROTO_CALIBRATION_liniar_calibration_message ntc_temp;
    uint16_t max_discharge_current; /* the max discharge current in mA */
    uint16_t max_charge_current; /* the max charge current in mA */
    uint16_t max_voltage; /* the max voltage in mV */
} UBA_PROTO_CALIBRATION_line_calibration_message;

typedef struct _UBA_PROTO_CALIBRATION_calibration_message {
    UBA_PROTO_CALIBRATION_line_calibration_message line_calibration[2];
} UBA_PROTO_CALIBRATION_calibration_message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default {0, 0}
#define UBA_PROTO_CALIBRATION_line_calibration_message_init_default {_UBA_PROTO_LINE_ID_MIN, {UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default}, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_default, 0, 0, 0}
#define UBA_PROTO_CALIBRATION_calibration_message_init_default {{UBA_PROTO_CALIBRATION_line_calibration_message_init_default, UBA_PROTO_CALIBRATION_line_calibration_message_init_default}}
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero {0, 0}
#define UBA_PROTO_CALIBRATION_line_calibration_message_init_zero {_UBA_PROTO_LINE_ID_MIN, {UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero}, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, UBA_PROTO_CALIBRATION_liniar_calibration_message_init_zero, 0, 0, 0}
#define UBA_PROTO_CALIBRATION_calibration_message_init_zero {{UBA_PROTO_CALIBRATION_line_calibration_message_init_zero, UBA_PROTO_CALIBRATION_line_calibration_message_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_slop_tag 1
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_y_intercept_tag 2
#define UBA_PROTO_CALIBRATION_line_calibration_message_id_tag 1
#define UBA_PROTO_CALIBRATION_line_calibration_message_vbat_tag 2
#define UBA_PROTO_CALIBRATION_line_calibration_message_vgen_tag 3
#define UBA_PROTO_CALIBRATION_line_calibration_message_vps_tag 4
#define UBA_PROTO_CALIBRATION_line_calibration_message_charge_current_tag 5
#define UBA_PROTO_CALIBRATION_line_calibration_message_discharge_current_tag 6
#define UBA_PROTO_CALIBRATION_line_calibration_message_amb_temp_tag 7
#define UBA_PROTO_CALIBRATION_line_calibration_message_ntc_temp_tag 8
#define UBA_PROTO_CALIBRATION_line_calibration_message_max_discharge_current_tag 9
#define UBA_PROTO_CALIBRATION_line_calibration_message_max_charge_current_tag 10
#define UBA_PROTO_CALIBRATION_line_calibration_message_max_voltage_tag 11
#define UBA_PROTO_CALIBRATION_calibration_message_line_calibration_tag 1

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    slop,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    y_intercept,       2)
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_CALLBACK NULL
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_DEFAULT NULL

#define UBA_PROTO_CALIBRATION_line_calibration_message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   FIXARRAY, MESSAGE,  vbat,              2) \
X(a, STATIC,   SINGULAR, MESSAGE,  vgen,              3) \
X(a, STATIC,   SINGULAR, MESSAGE,  vps,               4) \
X(a, STATIC,   SINGULAR, MESSAGE,  charge_current,    5) \
X(a, STATIC,   SINGULAR, MESSAGE,  discharge_current,   6) \
X(a, STATIC,   SINGULAR, MESSAGE,  amb_temp,          7) \
X(a, STATIC,   SINGULAR, MESSAGE,  ntc_temp,          8) \
X(a, STATIC,   SINGULAR, UINT32,   max_discharge_current,   9) \
X(a, STATIC,   SINGULAR, UINT32,   max_charge_current,  10) \
X(a, STATIC,   SINGULAR, UINT32,   max_voltage,      11)
#define UBA_PROTO_CALIBRATION_line_calibration_message_CALLBACK NULL
#define UBA_PROTO_CALIBRATION_line_calibration_message_DEFAULT NULL
#define UBA_PROTO_CALIBRATION_line_calibration_message_vbat_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_vgen_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_vps_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_charge_current_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_discharge_current_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_amb_temp_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message
#define UBA_PROTO_CALIBRATION_line_calibration_message_ntc_temp_MSGTYPE UBA_PROTO_CALIBRATION_liniar_calibration_message

#define UBA_PROTO_CALIBRATION_calibration_message_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, MESSAGE,  line_calibration,   1)
#define UBA_PROTO_CALIBRATION_calibration_message_CALLBACK NULL
#define UBA_PROTO_CALIBRATION_calibration_message_DEFAULT NULL
#define UBA_PROTO_CALIBRATION_calibration_message_line_calibration_MSGTYPE UBA_PROTO_CALIBRATION_line_calibration_message

extern const pb_msgdesc_t UBA_PROTO_CALIBRATION_liniar_calibration_message_msg;
extern const pb_msgdesc_t UBA_PROTO_CALIBRATION_line_calibration_message_msg;
extern const pb_msgdesc_t UBA_PROTO_CALIBRATION_calibration_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_fields &UBA_PROTO_CALIBRATION_liniar_calibration_message_msg
#define UBA_PROTO_CALIBRATION_line_calibration_message_fields &UBA_PROTO_CALIBRATION_line_calibration_message_msg
#define UBA_PROTO_CALIBRATION_calibration_message_fields &UBA_PROTO_CALIBRATION_calibration_message_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_CALIBRATION_UBA_PROTO_CALIBRATION_PB_H_MAX_SIZE UBA_PROTO_CALIBRATION_calibration_message_size
#define UBA_PROTO_CALIBRATION_calibration_message_size 248
#define UBA_PROTO_CALIBRATION_line_calibration_message_size 122
#define UBA_PROTO_CALIBRATION_liniar_calibration_message_size 10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
