/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_LINE.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UBA_PROTO_LINE_data_message, UBA_PROTO_LINE_data_message, AUTO)


PB_BIND(UBA_PROTO_LINE_adc_data_message, UBA_PROTO_LINE_adc_data_message, AUTO)


PB_BIND(UBA_PROTO_LINE_status, UBA_PROTO_LINE_status, AUTO)


PB_BIND(UBA_PROTO_LINE_command, UBA_PROTO_LINE_command, AUTO)






