/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_UBA_PROTO_DATA_LOG_UBA_PROTO_DATA_LOG_PB_H_INCLUDED
#define PB_UBA_PROTO_DATA_LOG_UBA_PROTO_DATA_LOG_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_BPT.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UBA_PROTO_DATA_LOG_data_log {
    uint32_t time; /* the time in ms of the log for the start of the test */
    uint8_t step_index; /* the index of the step in the BPT */
    uint8_t plan_index; /* the index of the plan in the TR */
    int16_t current; /* the current in mA negative for discharge and postive for charge */
    uint16_t voltage; /* the voltage in mV */
    int16_t temp; /* the temp of the battery in centi C */
} UBA_PROTO_DATA_LOG_data_log;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UBA_PROTO_DATA_LOG_data_log_init_default {0, 0, 0, 0, 0, 0}
#define UBA_PROTO_DATA_LOG_data_log_init_zero    {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define UBA_PROTO_DATA_LOG_data_log_time_tag     1
#define UBA_PROTO_DATA_LOG_data_log_step_index_tag 2
#define UBA_PROTO_DATA_LOG_data_log_plan_index_tag 3
#define UBA_PROTO_DATA_LOG_data_log_current_tag  4
#define UBA_PROTO_DATA_LOG_data_log_voltage_tag  5
#define UBA_PROTO_DATA_LOG_data_log_temp_tag     6

/* Struct field encoding specification for nanopb */
#define UBA_PROTO_DATA_LOG_data_log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   step_index,        2) \
X(a, STATIC,   SINGULAR, UINT32,   plan_index,        3) \
X(a, STATIC,   SINGULAR, INT32,    current,           4) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           5) \
X(a, STATIC,   SINGULAR, INT32,    temp,              6)
#define UBA_PROTO_DATA_LOG_data_log_CALLBACK NULL
#define UBA_PROTO_DATA_LOG_data_log_DEFAULT NULL

extern const pb_msgdesc_t UBA_PROTO_DATA_LOG_data_log_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UBA_PROTO_DATA_LOG_data_log_fields &UBA_PROTO_DATA_LOG_data_log_msg

/* Maximum encoded size of messages (where known) */
#define UBA_PROTO_DATA_LOG_UBA_PROTO_DATA_LOG_PB_H_MAX_SIZE UBA_PROTO_DATA_LOG_data_log_size
#define UBA_PROTO_DATA_LOG_data_log_size         38

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
