/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_BATTERY_UBA_BATTERY_PB_H_INCLUDED
#define PB_BATTERY_UBA_BATTERY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Battery_TYPE {
    Battery_TYPE_TYPE_NONE = 0,
    Battery_TYPE_TYPE_PRIMERY = 1,
    Battery_TYPE_TYPE_SECONDERY = 2,
    Battery_TYPE_TYPE_MAX = 3,
    Battery_TYPE_TYPE_INVALID = 4
} Battery_TYPE;

typedef enum _Battery_CELL_CHEMISTRY {
    Battery_CELL_CHEMISTRY_CELL_CHEMISTRY_LITHIUM_ION = 0,
    Battery_CELL_CHEMISTRY_CELL_CHEMISTRY_CUSTOM = 255
} Battery_CELL_CHEMISTRY;

/* Struct definitions */
typedef struct _Battery_Voltage_limits { /* in mV */
    int32_t min;
    int32_t nominal;
    int32_t max;
} Battery_Voltage_limits;

typedef struct _Battery_Capacity_limits { /* in mAh */
    int32_t min;
    int32_t max;
} Battery_Capacity_limits;

typedef struct _Battery_Temperature_limits { /* in C */
    float min;
    float max;
} Battery_Temperature_limits;

typedef struct _Battery_Cell {
    Battery_TYPE type;
    Battery_CELL_CHEMISTRY chemistry;
    pb_byte_t manufacturer[32];
    pb_byte_t part_number[32];
    Battery_Voltage_limits voltage;
    Battery_Capacity_limits capacity;
    Battery_Temperature_limits temperature;
} Battery_Cell;

typedef struct _Battery_Battery {
    Battery_TYPE type;
    char serial_number[10];
    uint8_t number_of_cells;
    uint32_t max_voltage; /* in mV */
} Battery_Battery;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Battery_TYPE_MIN Battery_TYPE_TYPE_NONE
#define _Battery_TYPE_MAX Battery_TYPE_TYPE_INVALID
#define _Battery_TYPE_ARRAYSIZE ((Battery_TYPE)(Battery_TYPE_TYPE_INVALID+1))

#define _Battery_CELL_CHEMISTRY_MIN Battery_CELL_CHEMISTRY_CELL_CHEMISTRY_LITHIUM_ION
#define _Battery_CELL_CHEMISTRY_MAX Battery_CELL_CHEMISTRY_CELL_CHEMISTRY_CUSTOM
#define _Battery_CELL_CHEMISTRY_ARRAYSIZE ((Battery_CELL_CHEMISTRY)(Battery_CELL_CHEMISTRY_CELL_CHEMISTRY_CUSTOM+1))




#define Battery_Cell_type_ENUMTYPE Battery_TYPE
#define Battery_Cell_chemistry_ENUMTYPE Battery_CELL_CHEMISTRY

#define Battery_Battery_type_ENUMTYPE Battery_TYPE


/* Initializer values for message structs */
#define Battery_Voltage_limits_init_default      {0, 0, 0}
#define Battery_Capacity_limits_init_default     {0, 0}
#define Battery_Temperature_limits_init_default  {0, 0}
#define Battery_Cell_init_default                {_Battery_TYPE_MIN, _Battery_CELL_CHEMISTRY_MIN, {0}, {0}, Battery_Voltage_limits_init_default, Battery_Capacity_limits_init_default, Battery_Temperature_limits_init_default}
#define Battery_Battery_init_default             {_Battery_TYPE_MIN, "", 0, 0}
#define Battery_Voltage_limits_init_zero         {0, 0, 0}
#define Battery_Capacity_limits_init_zero        {0, 0}
#define Battery_Temperature_limits_init_zero     {0, 0}
#define Battery_Cell_init_zero                   {_Battery_TYPE_MIN, _Battery_CELL_CHEMISTRY_MIN, {0}, {0}, Battery_Voltage_limits_init_zero, Battery_Capacity_limits_init_zero, Battery_Temperature_limits_init_zero}
#define Battery_Battery_init_zero                {_Battery_TYPE_MIN, "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Battery_Voltage_limits_min_tag           1
#define Battery_Voltage_limits_nominal_tag       2
#define Battery_Voltage_limits_max_tag           3
#define Battery_Capacity_limits_min_tag          1
#define Battery_Capacity_limits_max_tag          2
#define Battery_Temperature_limits_min_tag       1
#define Battery_Temperature_limits_max_tag       2
#define Battery_Cell_type_tag                    1
#define Battery_Cell_chemistry_tag               2
#define Battery_Cell_manufacturer_tag            3
#define Battery_Cell_part_number_tag             4
#define Battery_Cell_voltage_tag                 5
#define Battery_Cell_capacity_tag                6
#define Battery_Cell_temperature_tag             7
#define Battery_Battery_type_tag                 1
#define Battery_Battery_serial_number_tag        2
#define Battery_Battery_number_of_cells_tag      3
#define Battery_Battery_max_voltage_tag          4

/* Struct field encoding specification for nanopb */
#define Battery_Voltage_limits_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    min,               1) \
X(a, STATIC,   SINGULAR, INT32,    nominal,           2) \
X(a, STATIC,   SINGULAR, INT32,    max,               3)
#define Battery_Voltage_limits_CALLBACK NULL
#define Battery_Voltage_limits_DEFAULT NULL

#define Battery_Capacity_limits_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    min,               1) \
X(a, STATIC,   SINGULAR, INT32,    max,               2)
#define Battery_Capacity_limits_CALLBACK NULL
#define Battery_Capacity_limits_DEFAULT NULL

#define Battery_Temperature_limits_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    min,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    max,               2)
#define Battery_Temperature_limits_CALLBACK NULL
#define Battery_Temperature_limits_DEFAULT NULL

#define Battery_Cell_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UENUM,    chemistry,         2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, manufacturer,      3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, part_number,       4) \
X(a, STATIC,   SINGULAR, MESSAGE,  voltage,           5) \
X(a, STATIC,   SINGULAR, MESSAGE,  capacity,          6) \
X(a, STATIC,   SINGULAR, MESSAGE,  temperature,       7)
#define Battery_Cell_CALLBACK NULL
#define Battery_Cell_DEFAULT NULL
#define Battery_Cell_voltage_MSGTYPE Battery_Voltage_limits
#define Battery_Cell_capacity_MSGTYPE Battery_Capacity_limits
#define Battery_Cell_temperature_MSGTYPE Battery_Temperature_limits

#define Battery_Battery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   serial_number,     2) \
X(a, STATIC,   SINGULAR, UINT32,   number_of_cells,   3) \
X(a, STATIC,   SINGULAR, UINT32,   max_voltage,       4)
#define Battery_Battery_CALLBACK NULL
#define Battery_Battery_DEFAULT NULL

extern const pb_msgdesc_t Battery_Voltage_limits_msg;
extern const pb_msgdesc_t Battery_Capacity_limits_msg;
extern const pb_msgdesc_t Battery_Temperature_limits_msg;
extern const pb_msgdesc_t Battery_Cell_msg;
extern const pb_msgdesc_t Battery_Battery_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Battery_Voltage_limits_fields &Battery_Voltage_limits_msg
#define Battery_Capacity_limits_fields &Battery_Capacity_limits_msg
#define Battery_Temperature_limits_fields &Battery_Temperature_limits_msg
#define Battery_Cell_fields &Battery_Cell_msg
#define Battery_Battery_fields &Battery_Battery_msg

/* Maximum encoded size of messages (where known) */
#define BATTERY_UBA_BATTERY_PB_H_MAX_SIZE        Battery_Cell_size
#define Battery_Battery_size                     22
#define Battery_Capacity_limits_size             22
#define Battery_Cell_size                        144
#define Battery_Temperature_limits_size          10
#define Battery_Voltage_limits_size              33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
