/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_TR_UBA_PROTO_TR_PB_H_INCLUDED
#define PB_TR_UBA_PROTO_TR_PB_H_INCLUDED
#include <pb.h>
#include "UBA_PROTO_BPT.pb.h"
#include "UBA_Battery.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _TR_STEP_TYPE {
    TR_STEP_TYPE_STEP_TYPE_CHARGE = 0,
    TR_STEP_TYPE_STEP_TYPE_DISCHARGE = 1,
    TR_STEP_TYPE_STEP_TYPE_DELAY = 2,
    TR_STEP_TYPE_STEP_TYPE_LOOP = 3,
    TR_STEP_TYPE_STEP_TYPE_MAX = 4,
    TR_STEP_TYPE_STEP_TYPE_INVALID = 5
} TR_STEP_TYPE;

/* Struct definitions */
typedef struct _TR_Loop {
    uint8_t loop_to_step;
    uint16_t loop_size;
    uint16_t loop_counter;
} TR_Loop;

typedef struct _TR_config_step {
    TR_STEP_TYPE type_id;
    pb_size_t which_type;
    union {
        UBA_PROTO_BPT_charge charge;
        UBA_PROTO_BPT_discharge discharge;
        UBA_PROTO_BPT_delay delay;
        TR_Loop loop;
    } type;
} TR_config_step;

typedef struct _TR_Test_Routine {
    UBA_PROTO_BPT_MODE mode; /* the mode of the Test (single channels or dual channels */
    char name[32];
    uint8_t length;
    Battery_Battery battery;
    TR_config_step config[10];
    uint16_t log_interval; /* the logging interval in milisec */
} TR_Test_Routine;

typedef struct _TR_Test_Routine_Message {
    uint8_t index; /* the index in the test list */
    TR_Test_Routine tr; /* the Test Routine */
} TR_Test_Routine_Message;

typedef struct _TR_Test_Routine_File {
    TR_Test_Routine list[10];
} TR_Test_Routine_File;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TR_STEP_TYPE_MIN TR_STEP_TYPE_STEP_TYPE_CHARGE
#define _TR_STEP_TYPE_MAX TR_STEP_TYPE_STEP_TYPE_INVALID
#define _TR_STEP_TYPE_ARRAYSIZE ((TR_STEP_TYPE)(TR_STEP_TYPE_STEP_TYPE_INVALID+1))


#define TR_config_step_type_id_ENUMTYPE TR_STEP_TYPE

#define TR_Test_Routine_mode_ENUMTYPE UBA_PROTO_BPT_MODE




/* Initializer values for message structs */
#define TR_Loop_init_default                     {0, 0, 0}
#define TR_config_step_init_default              {_TR_STEP_TYPE_MIN, 0, {UBA_PROTO_BPT_charge_init_default}}
#define TR_Test_Routine_init_default             {_UBA_PROTO_BPT_MODE_MIN, "", 0, Battery_Battery_init_default, {TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default, TR_config_step_init_default}, 0}
#define TR_Test_Routine_Message_init_default     {0, TR_Test_Routine_init_default}
#define TR_Test_Routine_File_init_default        {{TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default, TR_Test_Routine_init_default}}
#define TR_Loop_init_zero                        {0, 0, 0}
#define TR_config_step_init_zero                 {_TR_STEP_TYPE_MIN, 0, {UBA_PROTO_BPT_charge_init_zero}}
#define TR_Test_Routine_init_zero                {_UBA_PROTO_BPT_MODE_MIN, "", 0, Battery_Battery_init_zero, {TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero, TR_config_step_init_zero}, 0}
#define TR_Test_Routine_Message_init_zero        {0, TR_Test_Routine_init_zero}
#define TR_Test_Routine_File_init_zero           {{TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero, TR_Test_Routine_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define TR_Loop_loop_to_step_tag                 1
#define TR_Loop_loop_size_tag                    2
#define TR_Loop_loop_counter_tag                 3
#define TR_config_step_type_id_tag               1
#define TR_config_step_charge_tag                2
#define TR_config_step_discharge_tag             3
#define TR_config_step_delay_tag                 4
#define TR_config_step_loop_tag                  5
#define TR_Test_Routine_mode_tag                 1
#define TR_Test_Routine_name_tag                 2
#define TR_Test_Routine_length_tag               3
#define TR_Test_Routine_battery_tag              4
#define TR_Test_Routine_config_tag               5
#define TR_Test_Routine_log_interval_tag         6
#define TR_Test_Routine_Message_index_tag        1
#define TR_Test_Routine_Message_tr_tag           2
#define TR_Test_Routine_File_list_tag            1

/* Struct field encoding specification for nanopb */
#define TR_Loop_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   loop_to_step,      1) \
X(a, STATIC,   SINGULAR, UINT32,   loop_size,         2) \
X(a, STATIC,   SINGULAR, UINT32,   loop_counter,      3)
#define TR_Loop_CALLBACK NULL
#define TR_Loop_DEFAULT NULL

#define TR_config_step_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type_id,           1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,charge,type.charge),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,discharge,type.discharge),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,delay,type.delay),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,loop,type.loop),   5)
#define TR_config_step_CALLBACK NULL
#define TR_config_step_DEFAULT NULL
#define TR_config_step_type_charge_MSGTYPE UBA_PROTO_BPT_charge
#define TR_config_step_type_discharge_MSGTYPE UBA_PROTO_BPT_discharge
#define TR_config_step_type_delay_MSGTYPE UBA_PROTO_BPT_delay
#define TR_config_step_type_loop_MSGTYPE TR_Loop

#define TR_Test_Routine_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   length,            3) \
X(a, STATIC,   SINGULAR, MESSAGE,  battery,           4) \
X(a, STATIC,   FIXARRAY, MESSAGE,  config,            5) \
X(a, STATIC,   SINGULAR, UINT32,   log_interval,      6)
#define TR_Test_Routine_CALLBACK NULL
#define TR_Test_Routine_DEFAULT NULL
#define TR_Test_Routine_battery_MSGTYPE Battery_Battery
#define TR_Test_Routine_config_MSGTYPE TR_config_step

#define TR_Test_Routine_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, MESSAGE,  tr,                2)
#define TR_Test_Routine_Message_CALLBACK NULL
#define TR_Test_Routine_Message_DEFAULT NULL
#define TR_Test_Routine_Message_tr_MSGTYPE TR_Test_Routine

#define TR_Test_Routine_File_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, MESSAGE,  list,              1)
#define TR_Test_Routine_File_CALLBACK NULL
#define TR_Test_Routine_File_DEFAULT NULL
#define TR_Test_Routine_File_list_MSGTYPE TR_Test_Routine

extern const pb_msgdesc_t TR_Loop_msg;
extern const pb_msgdesc_t TR_config_step_msg;
extern const pb_msgdesc_t TR_Test_Routine_msg;
extern const pb_msgdesc_t TR_Test_Routine_Message_msg;
extern const pb_msgdesc_t TR_Test_Routine_File_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TR_Loop_fields &TR_Loop_msg
#define TR_config_step_fields &TR_config_step_msg
#define TR_Test_Routine_fields &TR_Test_Routine_msg
#define TR_Test_Routine_Message_fields &TR_Test_Routine_Message_msg
#define TR_Test_Routine_File_fields &TR_Test_Routine_File_msg

/* Maximum encoded size of messages (where known) */
#define TR_Loop_size                             11
#define TR_Test_Routine_File_size                7690
#define TR_Test_Routine_Message_size             772
#define TR_Test_Routine_size                     766
#define TR_UBA_PROTO_TR_PB_H_MAX_SIZE            TR_Test_Routine_File_size
#define TR_config_step_size                      68

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
