/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_TR.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TR_Loop, TR_Loop, AUTO)


PB_BIND(TR_config_step, TR_config_step, AUTO)


PB_BIND(TR_Test_Routine, TR_Test_Routine, 2)


PB_BIND(TR_Test_Routine_Message, TR_Test_Routine_Message, 2)


PB_BIND(TR_Test_Routine_File, TR_Test_Routine_File, 4)




