/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_Battery.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Battery_Voltage_limits, Battery_Voltage_limits, AUTO)


PB_BIND(Battery_Capacity_limits, Battery_Capacity_limits, AUTO)


PB_BIND(Battery_Temperature_limits, Battery_Temperature_limits, AUTO)


PB_BIND(Battery_Cell, Battery_Cell, AUTO)


PB_BIND(Battery_Battery, Battery_Battery, AUTO)





