/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "UBA_PROTO_CMD.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UBA_PROTO_CMD_command_message, UBA_PROTO_CMD_command_message, AUTO)



